### ISSUE TITLE
VPC Support for ALB, NLB

### ISSUE THREAD

**Issue by kimxogus** [NaverCloudPlatform/terraform-provider-ncloud#138]
As documents, it seems alb and nlb are not supported in vpc environment as there's no type option.

Are alb and nlb supported in vpc environment?

https://registry.terraform.io/providers/NaverCloudPlatform/ncloud/latest/docs/resources/load_balancer

**Comment by iDevSK** [comment]
@kimxogus 
Unfortunately, we don't support VPC yet.
We will support VPC within a few months.

Thanks.

**Comment by sangkyu-kim** [comment]
I will going to handle issue #151, and it will release on 4, Mar.
Thanks.
