### ISSUE TITLE
No Region Data for region_code `SG

### ISSUE THREAD

**Issue by lanandra** [NaverCloudPlatform/terraform-provider-ncloud#194]
I have question regarding NCLOUD_REGION.
Tried to provision VPC on region Singapore (SG).

At terraform has stated variable ncloud_region:
```
variable "ncloud_region" {
  type             = string
  description = "NCloud Region"
  default        = "SG"
}
```

And called the variable on provider ncloud:

```
terraform {
  backend "remote" {
    hostname     = "app.terraform.io"
    organization = "my-organization"

    workspaces {
      name = "my-ncloud-vpc-workspace"
    }
  }
}

terraform {
  required_providers {
    ncloud = {
      source  = "NaverCloudPlatform/ncloud"
      version = "~> 2.2.2"
    }
  }
  required_version = ">= 1.1.5"
}

provider "ncloud" {
  region            = var.ncloud_region
  support_vpc = var.support_vpc
}
```

When i run terraform plan, i've got this error:
```
Error: no region data for region_code `SG`. please change region_code and try again
```

When i tried to change the value of var ncloud_region to KR, terraform plan can works.
Is it because region SG currently not supported from terraform provider NaverCloudPlatform/ncloud ?
Or i have mistakenly typed the region name/ID? my reference is from this [docs](https://www.ncloud.com/product/global/globalRegion)

**Comment by sangkyu-kim** [comment]
Hello Sir.
Please try to use `SGN` region code instead of `SG`
You can get regions for VPC below codes.
```hcl
data "ncloud_regions" "regions" {
  output_file = "region.json"
}
```
https://registry.terraform.io/providers/NaverCloudPlatform/ncloud/latest/docs/data-sources/regions

Thanks

**Comment by lanandra** [comment]
Hi @sangkyu-kim thanks for the information.
I have changed the region name to SGN and now terraform can provision VPC 🙏
