### ISSUE TITLE
VPC > NAT Gateway

### ISSUE THREAD

**Issue by YuSungDuk** [NaverCloudPlatform/terraform-provider-ncloud#20]
### Resource
- [x] resource_ncloud_network_nat_gateway

### Data Source
- [x] data_source_ncloud_nat_gateway

### API
- getNatGatewayInstanceList
- getNatGatewayInstanceDetail 
- createNatGatewayInstance 
- deleteNatGatewayInstance

**Comment by sangkyu-kim** [comment]
### Data Source
#### data_source_ncloud_nat_gateway

name | description | Computed | type | allow values
-- | -- | -- | -- | --
instance_no | NatGatewayInstanceNo | Required | string |  
name | NatGatewayName | Computed | string |  
description | NatGatewayDescription | Computed | string |  
vpc_no | VpcNo | Computed | string |  
zone | ZoneCode | Computed | string |  
public_ip | PublicIp | Computed | string |  
status | NatGatewayInstanceStatus | Computed | string | INIT \| CREATING \| RUN \| TERMTING

### Resource
#### resource_ncloud_network_nat_gateway

name | description | mandatory | type | allow values
-- | -- | -- | -- | --
vpc_no | VpcNo | Required<br>ForceNew | string |  
zone | ZoneCode | Required<br>ForceNew | string |  
name | NatGatewayName | Optional<br>ForceNew | string |  
description | NatGatewayDescription | Optional | string |  
instance_no | NatGatewayInstanceNo | Computed | string |  
public_ip | PublicIp | Computed | string |  
status | NatGatewayInstanceStatus | Computed | string | INIT \| CREATING \| RUN \| TERMTING

**Comment by sangkyu-kim** [comment]
### Common
#### Response
Name | Type | Description | Notes
------------ | ------------- | ------------- | -------------
**RequestId** | ***string** |  | [optional] [default to null]
**ReturnCode** | ***string** |  | [optional] [default to null]
**ReturnMessage** | ***string** |  | [optional] [default to null]
**TotalRows** | ***int32** |  | [optional] [default to null]
**NatGatewayInstanceList** | **[[]\*NatGatewayInstance](NatGatewayInstance.md)** |  | [optional] [default to null]

##### NatGatewayInstance

Name | Type | Description | Notes
------------ | ------------- | ------------- | -------------
**VpcName** | ***string** | VPC이름 | [optional] [default to null]
**NatGatewayInstanceNo** | ***string** | NATGateway인스턴스번호 | [optional] [default to null]
**NatGatewayName** | ***string** | NATGateway이름 | [optional] [default to null]
**PublicIp** | ***string** | 공인IP주소 | [optional] [default to null]
**NatGatewayInstanceStatus** | **[*CommonCode](CommonCode.md)** | NATGateway인스턴스상태 | [optional] [default to null]
**NatGatewayInstanceStatusName** | ***string** | NATGateway인스턴스상태이름 | [optional] [default to null]
**NatGatewayInstanceOperation** | **[*CommonCode](CommonCode.md)** | NATGateway인스턴스OP | [optional] [default to null]
**CreateDate** | ***string** | 생성일시 | [optional] [default to null]
**NatGatewayDescription** | ***string** | NATGateway설명 | [optional] [default to null]

### GetNatGatewayInstanceList
#### GetNatGatewayInstanceListRequest

Name | Type | Description | Notes
------------ | ------------- | ------------- | -------------
**RegionCode** | ***string** | REGION코드 | [optional] [default to null]
**NatGatewayInstanceNoList** | **[]\*string** | NATGateway인스턴스번호리스트 | [optional] [default to null]
**PublicIp** | ***string** | 공인IP주소 | [optional] [default to null]
**VpcName** | ***string** | VPC이름 | [optional] [default to null]
**NatGatewayName** | ***string** | natGatewayName | [optional] [default to null]
**NatGatewayInstanceStatusCode** | ***string** | NATGateway인스턴스상태코드 | [optional] [default to null]
**PageNo** | ***int32** | 페이지번호 | [optional] [default to null]
**PageSize** | ***int32** | 페이지사이즈 | [optional] [default to null]

### GetNatGatewayInstanceDetail
#### GetNatGatewayInstanceDetailRequest

Name | Type | Description | Notes
------------ | ------------- | ------------- | -------------
**RegionCode** | ***string** | REGION코드 | [optional] [default to null]
**NatGatewaInstanceNo** | ***string** | NATGatway인스턴스번호 | [default to null]

### CreateNatGatewayInstance
#### CreateNatGatewayInstanceRequest

Name | Type | Description | Notes
------------ | ------------- | ------------- | -------------
**RegionCode** | ***string** | REGION코드 | [optional] [default to null]
**NatGatewayDescription** | ***string** | NATGateway설명 | [optional] [default to null]
**NatGatewayName** | ***string** | NATGateway이름 | [optional] [default to null]
**VpcNo** | ***string** | VPC번호 | [default to null]
**ZoneCode** | ***string** | ZONE코드 | [default to null]

### DeleteNatGatewayInstance
#### DeleteNatGatewayInstanceRequest

Name | Type | Description | Notes
------------ | ------------- | ------------- | -------------
**RegionCode** | ***string** | REGION코드 | [optional] [default to null]
**NatGatewayInstanceNo** | ***string** | NATGateway인스턴스번호 | [default to null]

**Comment by sangkyu-kim** [comment]
- VpcNo 필요 

```json
{
  "getNatGatewayInstanceDetailResponse": {
    "requestId": "6f87ac05-15ea-4e36-8a39-57b116748b08",
    "returnCode": "0",
    "returnMessage": "success",
    "totalRows": 1,
    "natGatewayInstanceList": [
      {
        "vpcName": "dmz",
        "natGatewayInstanceNo": "1286343",
        "natGatewayName": "mynat",
        "publicIp": "101.101.221.74",
        "natGatewayInstanceStatus": {
          "code": "RUN",
          "codeName": "run"
        },
        "natGatewayInstanceStatusName": "운영중",
        "natGatewayInstanceOperation": {
          "code": "NULL",
          "codeName": "NULL OP"
        },
        "createDate": "2020-07-08T15:00:59+0900",
        "natGatewayDescription": "124",
        "zoneCode": "KR-1"
      }
    ]
  }
}
```
