### ISSUE TITLE
cannot set ACG to server

### ISSUE THREAD

**Issue by yunsoul** [NaverCloudPlatform/terraform-provider-ncloud#202]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform Ncloud Provider Version

```text
Terraform version : v1.1.8
Ncloud Provider version : v2.2.6
```

### Affected Resource(s)

* ncloud_server

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "ncloud_server" "server_test" {
  subnet_no                 = ncloud_subnet.subnet_test.id
  name                      = "test-server"
  server_image_product_code = "SW.VSVR.OS.LNX64.CNTOS.0703.B050"
  server_product_code       = "SVR.VSVR.STAND.C004.M016.NET.SSD.B050.G002"
  login_key_name            = ncloud_login_key.test_key.key_name
  access_control_group_configuration_no_list = [ncloud_access_control_group.acg_test.id]
}


locals {
  default_acg_rules_inbound = [
    ...
  ]
  default_acg_rules_outbound = [
     ...
  ]
}

resource "ncloud_access_control_group" "acg_test" {
  name       = "test-acg"
  vpc_no      = ncloud_vpc.test_vpc.id
}

resource "ncloud_access_control_group_rule" "acg_rule_test" {
  access_control_group_no = ncloud_access_control_group.acg_test.id
  dynamic "inbound" {
    for_each = local.default_acg_rules_inbound
    content {
      protocol    = inbound.value[0]
      ip_block    = inbound.value[1]
      port_range  = inbound.value[2]
      description = inbound.value[3]
    }
  }
  dynamic "outbound" {
    for_each = local.default_acg_rules_outbound
    content {
      protocol    = outbound.value[0]
      ip_block    = outbound.value[1]
      port_range  = outbound.value[2]
    }
  }
}
```

### Debug Output

**ncloud_server does not support vpc**

### Actual Behavior

ncloud_server에 ACG 설정(access_control_group_configuration_no_list)이 되지 않습니다.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by teacherSsamko** [comment]
Is it solved? 

document says it still supports only for classic 
https://registry.terraform.io/providers/NaverCloudPlatform/ncloud/latest/docs/resources/server
