### ISSUE TITLE
데이터 소스의 이름에 오류가 있습니다.

### ISSUE THREAD

**Issue by Jangab-water** [NaverCloudPlatform/terraform-provider-ncloud#204]
https://registry.terraform.io/providers/NaverCloudPlatform/ncloud/latest/docs/data-sources/nks_version

좌측의  documentation list에는 ncloud_nks_version이라고 나오는데, 실제로는 ncloud_nks_versions입니다.

**Comment by minosmlee** [comment]
v2.2.7에서 fix 되었습니다. 감사합니다.
