### ISSUE TITLE
Terraform Provider Development Program - Review

### ISSUE THREAD

**Issue by cgriggs01** [NaverCloudPlatform/terraform-provider-ncloud#21]
Hi Team,

My name is Chris, I'm a member of the Partner team @ HashiCorp.

I’ve taken a look at the provider here and would like to say great work so far! I do have one feedback item outlined below that I’d like to see addressed before we move on to the next steps. I’m opening this issues as a sort of checklist for tracking items and discussion.

 - [x] All of our official Terraform providers include a [MPL2](https://github.com/terraform-providers/terraform-provider-aws/blob/master/LICENSE) as the standard licensing. Can you make sure to add this and then we can move forward with the technical review.

I also want to include a list of best-practice requirements that has been defined by our Terraform engineering team:

### Terraform Provider Code Expectations/Conventions

 - [x] resource filename matches convention `resource_providername_resource_name.go`
 - [x] data source filename matches convention `data_source_providername_resource_name.go`
 - [x] we always let `d.Set()` to dereference pointers safely to avoid crashes, i.e. there's nothing like `d.Set(*variable)`
 - [x] flatteners and expanders are in `structures.go` + tests in `structures_test.go`
 - [x] any validation functions longer than a few lines are in `validators.go` + tests in `validators_test.go`
 - [x] `d.Set()` is called in any C/R/U/D for all available fields unless they're Computed-only (i.e. there are no orphans)
 - [x] all of `d.Set()`, `d.Get()`, `d.GetOk()`, `d.GetChange()` etc. use real field names (i.e. no typos)
 - [x] `d.Set()` is _always_ error-checked if it’s set, list or map
 - [x] `d.Set()` is _never_ error-checked if it's primitive data type (string, int, float, bool)
 - [x] Resource uses either `Read` or `Exists` function to remove resource from state if it's gone
 - [x] `d.Partial()` & `d.SetPartial()` are used any time there's more than 1 API call used to create or update a resource.
 - [x] `schema.ForceNew` is used for any field that is not updatable
 - [x] all field names are `lowercase_underscore`
 - [x] where possible data source fields match resource (e.g. when referencing `aws_instance` user shouldn't need to change anything - just add `data.` prefix)
 - [x] Constants are used if there are available in the upstream SDK (e.g. for status codes)
 - [x] `[INFO]` log message at least 2 per each C/R/U/D - e.g. creating (input), created (output)
 - [x] The provider code does not `panic`, always returns errors

Let me know if you have any questions.

Best,
Chris

**Comment by YuSungDuk** [comment]
@cgriggs01 I'll check your review. Thank you.

**Comment by YuSungDuk** [comment]
@cgriggs01 We added MPL2 LICENSE file. https://github.com/NaverCloudPlatform/terraform-provider-ncloud/blob/master/LICENSE.
Please check it.

**Comment by cgriggs01** [comment]
@YuSungDuk, 

The license looks great! I am going to run the acceptance test again. After the the provider will be ready for a deep technical review by a member of the Terraform ecosystem team. 

There will be one other provider ahead of you in the queue, but I expect that the review will begin in about 2-3 weeks.
