### ISSUE TITLE
Error: resource `ncloud_vpc` doesn't support classic

### ISSUE THREAD

**Issue by aplsms** [NaverCloudPlatform/terraform-provider-ncloud#216]
Just copy/pasted simple template and got an error:

```ncloud_vpc.vpc: Creating...
╷
│ Error: resource `ncloud_vpc` doesn't support classic
│
│   with ncloud_vpc.vpc,
│   on vpc.tf line 1, in resource "ncloud_vpc" "vpc":
│    1: resource "ncloud_vpc" "vpc" {
```

template:

```
resource "ncloud_vpc" "vpc" {
  ipv4_cidr_block = "172.16.240.0/22"
}

resource "ncloud_network_acl" "nacl" {
   vpc_no      = ncloud_vpc.vpc.id
   name        = "main"
 }
```

terraform plan complete successfully.

Any idea what is **classic**?

**Comment by gimmetm** [comment]
`classic` means non-vpc environment. 
Can you set `support_vpc = true` in Ncloud Provider?

https://registry.terraform.io/providers/NaverCloudPlatform/ncloud/latest/docs

**Comment by aplsms** [comment]
yes, that's a solution. is it possible to add note to the documentation?

**Comment by aplsms** [comment]
thank you, fixed.
