### ISSUE TITLE
unable to create instance SVR.VSVR.CPU.C002.M004.NET.SSD.B050.G002 using terraform.

### ISSUE THREAD

**Issue by aplsms** [NaverCloudPlatform/terraform-provider-ncloud#219]
Hello,

I can't create instance SVR.VSVR.CPU.C002.M004.NET.SSD.B050.G002 using terraform provider ncloud. but I can create such instance using web console.

instance configuration: 

```hcl
resource "ncloud_server" "elastic" {
  subnet_no                 = ncloud_subnet.subnet-pub1.id
  name                      = "${var.project_name}elastic"
  server_image_product_code = "SW.VSVR.OS.LNX64.CNTOS.0708.B050"
  login_key_name            = ncloud_login_key.key.key_name
  server_product_code       = "SVR.VSVR.CPU.C002.M004.NET.SSD.B050.G002"
  #access_control_group_configuration_no_list = [ncloud_access_control_group.vip.id]
  fee_system_type_code      = "MTRAT"
  network_interface {
        network_interface_no = ncloud_network_interface.elastic-nic.id
        order = 0
  }
}
```

error:

```
Error: Status: 400 Bad Request, Body: {"responseError": {
│   "returnCode": "1401",
│   "returnMessage": "Not found server product."
│ }}
│ 
│   with ncloud_server.elastic,
│   on elastic.tf line 2, in resource "ncloud_server" "elastic":
│    2: resource "ncloud_server" "elastic" {
│ 
```

list of available products got by https://registry.terraform.io/providers/NaverCloudPlatform/ncloud/latest/docs/data-sources/server_products

Region: KR
Versions:
Terraform v1.2.2
on darwin_arm64
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/navercloudplatform/ncloud v2.2.9

**Comment by minosmlee** [comment]
Hello! Thank you for your report!

Server Product code "SVR.VSVR.CPU.C002.M004.NET.SSD.B050.G002" is for "CPU Intensive" Type which is able to be installed on ZONE2. So check your Subnet ZONE is "2"

If you don't want to use "CPU Intensive", I recommand "HIGH CPU" type instead.

You can check difference between "CPU Intensive" and "HIGH CPU" from the link https://guide.ncloud-docs.com/docs/en/compute-server-prep

**Comment by aplsms** [comment]
I need just a cheap instance for  mongo arbiter.
when I changed CPU to HIGHCPU (without any other changes) it works fine.
