### ISSUE TITLE
VPC > Route Table

### ISSUE THREAD

**Issue by YuSungDuk** [NaverCloudPlatform/terraform-provider-ncloud#22]
### Resource
- [x] resource_ncloud_route_table
- [x] resource_ncloud_route
- [x] resource_ncloud_route_table_association

### Data Source
- [x] data_source_ncloud_route_table
- [x] data_source_ncloud_route_tables

### API
- getRouteTableList
- getRouteTableDetail
- createRouteTable
- deleteRouteTable
- getRouteList
- addRoute
- removeRoute
- getRouteTableSubnetList
- addRouteTableSubnet
- removeRouteTableSubnet

**Comment by sangkyu-kim** [comment]
### Resource
#### resource_ncloud_route_table

name | model | mandatory | type | allow values
-- | -- | -- | -- | --
vpc_no | VpcNo | Required | string |  
supported_subnet_type | SupportedSubnetTypeCode | Required | string | PUBLIC \| PRIVATE
name | RouteTableName | Optional | string |  
description | RouteTableDescription | Optional | string |  
status | RouteTableStatus | Computed | string | INIT \| CREATING \| RUN \| TERMTING
route_table_no | RouteTableNo | Computed | string |  
is_default | IsDefault | Computed | bool |  


#### resource_ncloud_route_table_association

name | model | mandatory | type | allow values
-- | -- | -- | -- | --
route_table_no | RouteTableNo | Required | string |  
destination_cidr_block | DestinationCidrBlock | Required | string |  
target_type | TargetType | Required | string | NATGW \| VPCPEERING \| VGW
target_no | TargetNo | Optional | string |  
target_name | TargetName | Optional | string |  


### Data Source
#### data_source_ncloud_route_table
#### data_source_ncloud_route_tables

**Comment by sangkyu-kim** [comment]
## Route Table

### Common
#### Response

Name | Type | Description | Notes
------------ | ------------- | ------------- | -------------
**RequestId** | ***string** |  | [optional] [default to null]
**ReturnCode** | ***string** |  | [optional] [default to null]
**ReturnMessage** | ***string** |  | [optional] [default to null]
**TotalRows** | ***int32** |  | [optional] [default to null]
**RouteTableList** | **[[]\*RouteTable](RouteTable.md)** |  | [optional] [default to null]

##### RouteTable

Name | Type | Description | Notes
------------ | ------------- | ------------- | -------------
**RouteTableNo** | ***string** | 라우트테이블번호 | [optional] [default to null]
**RouteTableName** | ***string** | 라우트테이블이름 | [optional] [default to null]
**RegionCode** | ***string** | REGION코드 | [optional] [default to null]
**VpcNo** | ***string** | VPC번호 | [optional] [default to null]
**SupportedSubnetType** | **[*CommonCode](CommonCode.md)** | 지원하는서브넷유형 | [optional] [default to null]
**IsDefault** | ***bool** | Default여부 | [optional] [default to null]
**RouteTableStatus** | **[*CommonCode](CommonCode.md)** | 라우트테이블상태 | [optional] [default to null]
**RouteTableDescription** | ***string** | 라우트테이블설명 | [optional] [default to null]

### GetRouteTableList
#### GetRouteTableListRequest

Name | Type | Description | Notes
------------ | ------------- | ------------- | -------------
**RegionCode** | ***string** | REGION코드 | [optional] [default to null]
**RouteTableNoList** | **[]\*string** | 라우트테이블번호리스트 | [optional] [default to null]
**RouteTableName** | ***string** | 라우트테이블이름 | [optional] [default to null]
**SupportedSubnetTypeCode** | ***string** | 지원하는서브넷유형코드 | [optional] [default to null]
**PageNo** | ***int32** | 페이지번호 | [optional] [default to null]
**PageSize** | ***int32** | 페이지사이즈 | [optional] [default to null]
**SortedBy** | ***string** | 정렬대상 | [optional] [default to null]
**SortingOrder** | ***string** | 정렬순서 | [optional] [default to null]
**VpcNo** | ***string** | VPC번호 | [optional] [default to null]

### GetRouteTableDetail
#### GetRouteTableDetailRequest

Name | Type | Description | Notes
------------ | ------------- | ------------- | -------------
**RegionCode** | ***string** | REGION코드 | [optional] [default to null]
**RouteTableNo** | ***string** | 라우트테이블번호 | [default to null]

### CreateRouteTable
#### CreateRouteTableRequest

Name | Type | Description | Notes
------------ | ------------- | ------------- | -------------
**RegionCode** | ***string** | REGION코드 | [optional] [default to null]
**RouteTableDescription** | ***string** | 라우트테이블설명 | [optional] [default to null]
**SupportedSubnetTypeCode** | ***string** | 지원하는서브넷유형코드 | [default to null]
**RouteTableName** | ***string** | 라우트테이블이름 | [optional] [default to null]
**VpcNo** | ***string** | VPC번호 | [default to null]

#### DeleteRouteTable
#### DeleteRouteTableRequest

Name | Type | Description | Notes
------------ | ------------- | ------------- | -------------
**RegionCode** | ***string** | REGION코드 | [optional] [default to null]
**RouteTableNo** | ***string** | 라우트테이블번호 | [default to null]

**Comment by sangkyu-kim** [comment]
## Route
### Common
#### Response

Name | Type | Description | Notes
------------ | ------------- | ------------- | -------------
**RequestId** | ***string** |  | [optional] [default to null]
**ReturnCode** | ***string** |  | [optional] [default to null]
**ReturnMessage** | ***string** |  | [optional] [default to null]
**TotalRows** | ***int32** |  | [optional] [default to null]
**RouteList** | **[[]\*Route](Route.md)** |  | [optional] [default to null]

##### Route

Name | Type | Description | Notes
------------ | ------------- | ------------- | -------------
**DestinationCidrBlock** | ***string** | 목적지CIDR블록 | [optional] [default to null]
**TargetName** | ***string** | 목적지이름 | [optional] [default to null]
**RouteTableNo** | ***string** | 라우트테이블번호 | [optional] [default to null]
**TargetType** | **[*CommonCode](CommonCode.md)** | 목적지유형 | [optional] [default to null]
**TargetNo** | ***string** | 목적지번호 | [optional] [default to null]
**IsDefault** | ***bool** | Default여부 | [optional] [default to null]


### AddRoute
#### AddRouteRequest

Name | Type | Description | Notes
------------ | ------------- | ------------- | -------------
**RegionCode** | ***string** | REGION코드 | [optional] [default to null]
**RouteList** | **[[]\*RouteParameter](RouteParameter.md)** | 라우트리스트 | [default to null]
**RouteTableNo** | ***string** | 라우트테이블번호 | [default to null]
**VpcNo** | ***string** | VPC번호 | [default to null]

### RemoveRoute
#### RemoveRouteRequest

Name | Type | Description | Notes
------------ | ------------- | ------------- | -------------
**RegionCode** | ***string** | REGION코드 | [optional] [default to null]
**RouteList** | **[[]\*RouteParameter](RouteParameter.md)** | 라우트리스트 | [default to null]
**RouteTableNo** | ***string** | 라우트테이블번호 | [default to null]
**VpcNo** | ***string** | VPC번호 | [default to null]

**Comment by sangkyu-kim** [comment]
## Route Table Subnet
### Common
#### Response

Name | Type | Description | Notes
------------ | ------------- | ------------- | -------------
**RequestId** | ***string** |  | [optional] [default to null]
**ReturnCode** | ***string** |  | [optional] [default to null]
**ReturnMessage** | ***string** |  | [optional] [default to null]
**TotalRows** | ***int32** |  | [optional] [default to null]
**SubnetList** | **[[]\*Subnet](Subnet.md)** |  | [optional] [default to null]

#### Subnet

Name | Type | Description | Notes
------------ | ------------- | ------------- | -------------
**SubnetNo** | ***string** | 서브넷번호 | [optional] [default to null]
**VpcNo** | ***string** | VPC번호 | [optional] [default to null]
**ZoneCode** | ***string** | ZONE코드 | [optional] [default to null]
**SubnetName** | ***string** | 서브넷이름 | [optional] [default to null]
**Subnet** | ***string** | 서브넷 | [optional] [default to null]
**SubnetStatus** | **[*CommonCode](CommonCode.md)** | 서브넷상태 | [optional] [default to null]
**CreateDate** | ***string** | 생성일시 | [optional] [default to null]
**SubnetType** | **[*CommonCode](CommonCode.md)** | 서브넷유형 | [optional] [default to null]
**UsageType** | **[*CommonCode](CommonCode.md)** | 용도유형 | [optional] [default to null]
**NetworkAclNo** | ***string** | 네트워크ACL번호 | [optional] [default to null]

### GetRouteTableSubnetList
#### GetRouteTableSubnetListRequest

Name | Type | Description | Notes
------------ | ------------- | ------------- | -------------
**RegionCode** | ***string** | REGION코드 | [optional] [default to null]
**RouteTableNo** | ***string** | 라우트테이블번호 | [default to null]

### AddRouteTableSubnet
#### AddRouteTableSubnetRequest

Name | Type | Description | Notes
------------ | ------------- | ------------- | -------------
**RegionCode** | ***string** | REGION코드 | [optional] [default to null]
**RouteTableNo** | ***string** | 라우트테이블번호 | [default to null]
**SubnetNoList** | **[]\*string** | 서브넷번호리스트 | [default to null]
**VpcNo** | ***string** | VPC번호 | [default to null]

### RemoveRouteTableSubnet
#### RemoveRouteTableSubnetRequest

Name | Type | Description | Notes
------------ | ------------- | ------------- | -------------
**RegionCode** | ***string** | REGION코드 | [optional] [default to null]
**RouteTableNo** | ***string** | 라우트테이블번호 | [default to null]
**SubnetNoList** | **[]\*string** | 서브넷번호리스트 | [default to null]
**VpcNo** | ***string** | VPC번호 | [default to null]
