### ISSUE TITLE
Load banaler on VPC.

### ISSUE THREAD

**Issue by aplsms** [NaverCloudPlatform/terraform-provider-ncloud#220]
Hello,
Trying to create Application Load balancer using terraform.
Asked support about it.

Got answer from support:
-------------------------------8<-----------------------------
Thank you for contacting NAVER Cloud Platform.
 
Terraform does not provide steps on how to create a load balancer.
 
To create a load balancer from the NAVER Cloud Platform console, please refer to the guide below
 
- Follow the link: https://guide.ncloud-docs.com/docs/en/networking-loadbalancer-loadbalanceroverview
 
Reach us at Customer Support if you have further questions.
Thank you.
-------------------------------8<-----------------------------

So:
1. can I create Load balancer on VPC using terraform? example looks like related to classic...
2. can I create certificate in certificate manager, using terraform? example looks like related to classic and don't work on VPC.

Thank you.

**Comment by sangkyu-kim** [comment]
Hello
https://registry.terraform.io/providers/NaverCloudPlatform/ncloud/latest/docs/resources/lb

**Comment by sangkyu-kim** [comment]
Hello, 
I'm responsible Terraform on NAVER CLOUD PLATFORM.

A1. You can refer below links
- https://registry.terraform.io/providers/NaverCloudPlatform/ncloud/latest/docs/resources/lb
- https://registry.terraform.io/providers/NaverCloudPlatform/ncloud/latest/docs/resources/lb_listener
- https://registry.terraform.io/providers/NaverCloudPlatform/ncloud/latest/docs/resources/lb_target_group
- https://registry.terraform.io/providers/NaverCloudPlatform/ncloud/latest/docs/resources/lb_target_group_attachment

A2. Certificate manager doesn't support on VPC now

Thanks.

**Comment by wonchulee** [comment]
Close the issue as it seems to have been resolved. If you have any questions, feel free to open up the issue.
