### ISSUE TITLE
Cloud DB for MySQL Status

### ISSUE THREAD

**Issue by KISMIDEV** [NaverCloudPlatform/terraform-provider-ncloud#224]
안녕하세요.

Cloud DB for MySQL 리소스의 Terraform 템플릿을 만들기 위해서 Go로 `resource_nlcoud_vmysql`을 작성하고 있습니다.
SDK를 사용해서 Cloud DB for MySQL의 CRUD 뼈대를 Golnag으로 작성했고 `make build` 후 리소스를 배포했습니다.
CloudMysqlInstanceStatus 값을 사용해서 리소스가 생성됐는지 확인하도록 코드를 작성한 경우, `terraform apply` 가 성공해서 콘솔에는 리소스가 정상적으로 생성된 것으로 확인되는데 CLI 상에서는 Pending 상태가 지속됩니다.
```
func waitStateNcloudVmysqlForCreation(config *ProviderConfig, id string) error {
	stateConf := &resource.StateChangeConf{
		Pending: []string{"INIT", "CREAT"},
		Target:  []string{"RUN"},
		Refresh: func() (interface{}, string, error) {
			vmysql, err := getVmysqlInstance(config, id)
			if err != nil {
				return 0, "", err
			}
			return vmysql, ncloud.StringValue(vmysql.CloudMysqlInstanceStatusName), nil
		},
		Timeout:    DefaultCreateTimeout,
		Delay:      2 * time.Second, // 20min
		MinTimeout: 2 * time.Second, // 30min
	}

	_, err := stateConf.WaitForState()
	if err != nil {
		return fmt.Errorf("error waiting for VmysqlInstance state to be \"RUN\": %s", err)
	}

	return nil
}
```

<br>그리고 Pending 상태가 끝나면 아래와 같은 오류가 발생합니다. Pending 상태에서 오류로 넘어가기 때문에 콘솔에서는 정삭적으로 배포된 리소스가 `terraform.tfstate` 파일에 기록되지 않아 관리하는 부분에서 문제가 발생합니다.
![image](https://user-images.githubusercontent.com/70998863/178459675-7fa103de-2e8a-40b5-a5aa-d2b125f15eb3.png)

<br>CloudMysqlInstanceStatusName을 사용해서 아래와 같이 코드를 작성한 경우에는 apply가 성공하고 리소스가 정상적으로 만들어집니다.
```
func waitStateNcloudVmysqlForCreation(config *ProviderConfig, id string) error {
	stateConf := &resource.StateChangeConf{
		Pending: []string{"settingUp", "creating"},
		Target:  []string{"running"},
		Refresh: func() (interface{}, string, error) {
			vmysql, err := getVmysqlInstance(config, id)
			if err != nil {
				return 0, "", err
			}
			return vmysql, ncloud.StringValue(vmysql.CloudMysqlInstanceStatusName), nil
		},
		Timeout:    DefaultCreateTimeout,
		Delay:      2 * time.Second, // 20min
		MinTimeout: 2 * time.Second, // 30min
	}

	_, err := stateConf.WaitForState()
	if err != nil {
		return fmt.Errorf("error waiting for VmysqlInstance state to be \"RUN\": %s", err)
	}

	return nil
}
```

<br>MySQL  DB 서비스의 CloudMysqlInstanceStatus가 업데이트가 되는 과정에 문제가 있다고 생각됩니다.
업데이트하는 과정에 문제가 없는지 확인해주시면 감사하겠습니다.

Terraform과 Go Version은 아래와 같습니다.
- Go Version: 1.16.4
- Terraform Version: 1.2.4

**Comment by minosmlee** [comment]
안녕하세요

Cloud DB for MySQW 인스턴스를 생성하신 뒤 생성 완료 체크를 위해 
`cloudMysqlInstanceStatus`와 `cloudMysqlInstanceStatusName`을 사용하셨군요

아래 스크린샷을 보시면 `cloudMysqlInstanceStatus` 에는 `RUN`이라는 상태코드가 존재하지 않는 부분으로 인해 Target 상태에 진입하지 못한것으로 보입니다.
![image](https://user-images.githubusercontent.com/52672287/178657283-cdae5904-583e-4efd-98f4-5ddc6a56668b.png)

두번째 사용하신 `cloudMysqlInstanceStatusName`은 `cloudMysqlInstanceStatus`과 `cloudMysqlInstanceOperation` 의 조합으로 이루어집니다.

따라서  `cloudMysqlInstanceStatusName : running`  = `cloudMysqlInstanceStatus : CREAT` x `cloudMysqlInstanceOperation :  NULL` 로 이루어져있습니다.

원하시는 동작을 위해 `cloudMysqlInstanceStatus` 보다는 `cloudMysqlInstanceStatusName` 를 사용하시는것이 더 적절한것 같습니다. `cloudMysqlInstanceStatusName`이 콘솔에 노출되는 상태값과 정확히 일치하게끔 되어있습니다.


감사합니다.

**Comment by wonchulee** [comment]
@minosmlee 님의 답변으로 해결된 것으로 보여 이슈를 정리합니다. 혹시 추가 확인이 필요한 부분이 있다면 다시 이슈를 오픈해주세요. 감사합니다.
