### ISSUE TITLE
Cloud DB for Redis Config Group

### ISSUE THREAD

**Issue by KISMIDEV** [NaverCloudPlatform/terraform-provider-ncloud#225]
안녕하세요.

Cloud DB for Redis Config Group 리소스의 Terraform 템플릿을 만들기 위해서 Go로 `resource_nlcoud_vredis_config_group`을 작성하고 있습니다. SDK를 사용해서 ConfigGroup의 CRUD를 작성하고 테스트하는 과정에서 문제가 발생했습니다.

Terraform으로 `resource_nlcoud_vredis_config_group`을 배포하고 삭제하는 과정에서 아래와 같은 오류가 발생했습니다.
![image](https://user-images.githubusercontent.com/70998863/179123430-545ec396-a2d0-4b3b-a3b5-e6b75f89f8a2.png)

<br>오류 내용대로 SDK의 DeleteCloudRedisConfigGroupResponse.cloudRedisConfigGroupList에서 확인해 보니
아래와 같이 cloudRedisConfigGroupList라는 Argument가 있는 것으로 확인됩니다.
![image](https://user-images.githubusercontent.com/70998863/179123649-af434cf7-e224-4c5f-b69c-c6f3b2939d4c.png)

<br>cloudRedisConfigGroupList로 이동하면 아래와 같이 NotFound error가 발생합니다.
![image](https://user-images.githubusercontent.com/70998863/179123714-c41a6700-ca17-44e1-a76d-2903ea7af368.png)

CreateCloudRedisConfigGroupResponse, GetCloudRedisConfigGroupResponse의 경우, 정상적으로 CloudRedisConfigGroupList를 가져오는것으로 봐서 DeleteCloudRedisConfigGroupResponse의 CloudRedisConfigGroupList 때문에 오류가 발생한 것으로 생각됩니다. 
이 부분 확인하고 답변 주시면 감사하겠습니다.

Terraform과 Go Version은 아래와 같습니다.
- Go Version: 1.16.4
- Terraform Version: 1.2.4

ConfigGroup을 삭제하는 코드는 아래와 같습니다.
```
func resourceNcloudVredisConfigGroupDelete(d *schema.ResourceData, meta interface{}) error {
	config := meta.(*ProviderConfig)

	if err := terminateThenWaitVredisConfigGroup(config, d.Id()); err != nil {
		return err
	}
	d.SetId("")
	return nil
}

func terminateThenWaitVredisConfigGroup(config *ProviderConfig, id string) error {
	var err error

	stateConf := &resource.StateChangeConf{
		Pending: []string{"running", "deleting"},
		Target:  []string{"deleted"},
		Refresh: func() (interface{}, string, error) {
			configGroup, err := getVredisConfigGroup(config, id)

			if err != nil {
				return 0, "", err
			}
			if configGroup == nil { // Instance is terminated.
				return configGroup, "TERMINATED", nil
			}
			return configGroup, ncloud.StringValue(configGroup.ConfigGroupStatusName), nil
		},
		Timeout:    DefaultTimeout,
		Delay:      2 * time.Second,
		MinTimeout: 3 * time.Second,
	}

	err = terminateVredisConfigGroup(config, id)
	if err != nil {
		return err
	}

	_, err = stateConf.WaitForState()
	// if err != nil {
	// 	return fmt.Errorf("error waiting for VmysqlInstance state to be \"TERMINATED\": %s", err)
	// }

	return nil
}

func terminateVredisConfigGroup(config *ProviderConfig, id string) error {
	reqParams := &vredis.DeleteCloudRedisConfigGroupRequest{
		RegionCode:    &config.RegionCode,
		ConfigGroupNo: ncloud.String(id),
	}

	logCommonRequest("terminateVredisConfigGroup", reqParams)
	resp, err := config.Client.vredis.V2Api.DeleteCloudRedisConfigGroup(reqParams)
	logResponse("terminateVredisConfigGroup", resp)

	if err != nil {
		logErrorResponse("terminateVredisConfigGroup", err, reqParams)
		return err
	}

	return nil
}
```

**Comment by yoogledev** [comment]
@KISMIDEV 님 안녕하세요.
현재 [ncloud go sdk](https://github.com/NaverCloudPlatform/ncloud-sdk-go-v2) `DeleteCloudRedisConfigGroupResponse` 해당 모델의 `CloudRedisConfigGroupList` 필드 타입이 잘못 적용된 것으로 확인됩니다.

해당 부분 현재 수정 예정이고, 수정 및 다음 버전으로 릴리즈가 완료되면 해당 버전으로 ncloud go sdk를 업그레이드하셔서 사용하시면 됩니다.
수정된 버전의 go sdk가 릴리즈되면 한번 더 말씀드리겠습니다. PR [#25](https://github.com/NaverCloudPlatform/ncloud-sdk-go-v2/pull/25)

**Comment by KISMIDEV** [comment]
@yoogle96 답변 감사합니다.

혹시 다음 버전 릴리즈가 언제쯤 계획되어있는지 알 수 있을까요?!
만약 8월쯤 예정이시면 우선 작성 완료된 부분까지 먼저 PR을 요청해도 괜찮을까요?

**Comment by wonchulee** [comment]
안녕하세요, 해결된 이슈로 클로즈 합니다. 혹시 문제가 있다면 다시 오픈해주시기 바랍니다.
