### ISSUE TITLE
[ncloud_network_acl_rule] required 'ip_block' in spite of 'deny_allow_group_no' provided.

### ISSUE THREAD

**Issue by civilizeddev** [NaverCloudPlatform/terraform-provider-ncloud#230]
### Terraform CLI and Terraform Ncloud Provider Version

- Terraform version: 1.2.5
- Ncloud Provider version: 2.2.9

### Affected Resource(s)

* ncloud_network_acl_rule

### Script

```typescript
export class MyVpc extends TerraformStack {
  constructor(scope: Construct, id: string) {
    super(scope, id)
    
    // ...

    const vpc = new Vpc(this, 'vpc', {
      ipv4CidrBlock: '192.168.0.0/16',
    })

    const sshUsers = new NetworkAclDenyAllowGroup(this, 'ssh-users', {
      vpcNo: vpc.vpcNo,
      ipList: ['123.123.123.123'],
    })

    new NetworkAclRule(this, 'network-acl-rule', {
      networkAclNo: vpc.defaultNetworkAclNo,
      inbound: [
        {
          priority: 100,
          ruleAction: 'ALLOW',
          protocol: 'TCP',
          portRange: '22',
          denyAllowGroupNo: sshUsers.networkAclDenyAllowGroupNo,
        },
      ],
    })
  }
}
```

### Panic Output

```
Inappropriate value for attribute "inbound": element 0: attribute "ip_block" is required.
```

### Expected Behavior

it should work without `ip_block'.

- ip_block: (Optional, Required if deny_allow_group_no is not provided)
- deny_allow_group_no: (Optional, Required if ip_block is not provided)

### Actual Behavior

failed.

### Steps to Reproduce

1. `cdktf deploy`

### References

- https://registry.terraform.io/providers/NaverCloudPlatform/ncloud/latest/docs/resources/network_acl_rule

**Comment by youngmn** [comment]
테스트한 결과 정상 동작합니다. 이슈는 클로즈 하겠습니다.
추가 질문 있으시면 re-open 부탁드리겠습니다.
