### ISSUE TITLE
ncloud_nks_cluster의 Attributes reference에 cluster_acg_no가 추가되어야 합니다.

### ISSUE THREAD

**Issue by Jangab-water** [NaverCloudPlatform/terraform-provider-ncloud#233]
현재 NKS를 프로비저닝할 경우, 사용자가 수동으로 ACG를 생성할 수 있는 방법이 전혀 없습니다.

따라서, 이미 NKS가 생성된 이후 data로 생성된 NKS 관련 리소스를 끌어와야 하는데, 
1. NKS 신청으로 자동생성되는 ACG의 경우 cluster_uuid나 node_pool의 instance_no 등과는 전혀 관련이 없는 랜덤한 값을 `nks-` 라는 공통 prefix 뒤에 덧붙여 생성합니다. 따라서 이름으로 data를 끌어올 수 없습니다.
2. `ncloud_nks_cluster` 및 `ncloud_node_pool`의 경우 Attribute로 ACG의 ID값을 포함하고 있지 않습니다. 따라서 ID 기준으로 가져올 수 없습니다.

ACG의 경우 노드 풀이 아니라 클러스터가 구축되면서 자동생성되도록 트리거 되어있는 것 같은데, 그렇다면 ncloud_nks_cluster 리소스 생성시 Attribute로 `cluster_acg_no` 를 추가하여 NKS 관련 ACG를 수정할 수 있도록 방안을 마련해주셨으면 합니다.

감사합니다.

**Comment by azamara** [comment]
안녕하세요. 

현재 Terraform에서 사용 중인 NKS Open API에 `acg_no` 변수 추가가 필요합니다.
Open API 배포 후 11월 4일에 `acg_no` 정보가 추가된 버전으로 반영될 예정입니다. 

좋은 의견 남겨주셔서 감사합니다.

**Comment by gimmetm** [comment]
안녕하세요.

답변드린 기능 제공이 내부 사정으로 인해 연기되어 추가 안내 드립니다.

Kubernetes Service(Terraform)
- ncloud_nks_cluster 리소스의 acg_no attribute 추가
- ncloud_nks_node_pool 리소스의 노드 관련 정보 추가

2022년 11월 4일 반영 예정이었으나 2022년 11월 23일 적용될 예정입니다.

감사합니다.

**Comment by Jangab-water** [comment]
답변 확인했습니다.

acg_no 추가 후 이슈는 닫겠습니다.

감사합니다.
