### ISSUE TITLE
Need "how to test".

### ISSUE THREAD

**Issue by jclab-joseph** [NaverCloudPlatform/terraform-provider-ncloud#245]
We can test on real infrastructure with TF_ACC=1 and Access Key.
However, as testing, may see that the test fails due to the limit of the number of VPCs.
Also, if the test fails, the infrastructure involved will not be properly deleted.

Documentation of proper testing methods is required.

If gracefully testing is not possible, then community support working within limited resources is almost impossible.

**Comment by wonchulee** [comment]
Hello, and thanks for your comments.
As you mentioned, we are conscious of the problem with using the Terraform acceptance test to test resources. Although it's difficult to say when, we'll try to do so in the future.

**Comment by wonchulee** [comment]
If you have any questions, please re-open this issue.
