### ISSUE TITLE
VServer > Placement Group

### ISSUE THREAD

**Issue by YuSungDuk** [NaverCloudPlatform/terraform-provider-ncloud#25]
#### Resource
- [x] resource_ncloud_placement_group (New)

#### Data Source
- [x] data_source_ncloud_placement_group (New)

#### API
- getPlacementGroupList  
- getPlacementGroupDetail 
- createPlacementGroup
- deletePlacementGroup  
- addPlacementGroupServerInstance 
- removePlacementGroupServerInstance

**Comment by sangkyu-kim** [comment]
#### Response

Name | Type | Description | Notes
------------ | ------------- | ------------- | -------------
**RequestId** | ***string** |  | [optional] [default to null]
**ReturnCode** | ***string** |  | [optional] [default to null]
**ReturnMessage** | ***string** |  | [optional] [default to null]
**TotalRows** | ***int32** |  | [optional] [default to null]
**PlacementGroupList** | **[[]\*PlacementGroup](PlacementGroup.md)** |  | [optional] [default to null]

##### PlacementGroup

Name | Type | Description | Notes
------------ | ------------- | ------------- | -------------
**PlacementGroupNo** | ***string** | 물리배치그룹번호 | [optional] [default to null]
**PlacementGroupName** | ***string** | 물리배치그룹이름 | [optional] [default to null]
**PlacementGroupType** | **[*CommonCode](CommonCode.md)** | 물리배치그룹유형 | [optional] [default to null]

#### GetPlacementGroupListRequest

Name | Type | Description | Notes
------------ | ------------- | ------------- | -------------
**RegionCode** | ***string** | REGION코드 | [optional] [default to null]
**PlacementGroupName** | ***string** | 물리배치그룹이름 | [optional] [default to null]
**PlacementGroupNoList** | **[]\*string** | 물리배치그룹번호리스트 | [optional] [default to null]

#### GetPlacementGroupDetailRequest

Name | Type | Description | Notes
------------ | ------------- | ------------- | -------------
**RegionCode** | ***string** | REGION코드 | [optional] [default to null]
**PlacementGroupNo** | ***string** | 물리배치그룹번호리스트 | [default to null]

#### CreatePlacementGroupRequest

Name | Type | Description | Notes
------------ | ------------- | ------------- | -------------
**RegionCode** | ***string** | REGION코드 | [optional] [default to null]
**PlacementGroupName** | ***string** | 물리배치그룹이름 | [optional] [default to null]
**PlacementGroupTypeCode** | ***string** | 물리배치그룹유형코드 | [optional] [default to null]

#### DeletePlacementGroupRequest
Name | Type | Description | Notes
------------ | ------------- | ------------- | -------------
**RegionCode** | ***string** | REGION코드 | [optional] [default to null]
**PlacementGroupNo** | ***string** | 물리배치그룹번호 | [default to null]

#### AddPlacementGroupServerInstanceRequest

Name | Type | Description | Notes
------------ | ------------- | ------------- | -------------
**RegionCode** | ***string** | REGION코드 | [optional] [default to null]
**PlacementGroupNo** | ***string** | 물리배치그룹번호 | [default to null]
**ServerInstanceNo** | ***string** | 서버인스턴스번호 | [default to null]

#### DeletePlacementGroupRequest

Name | Type | Description | Notes
------------ | ------------- | ------------- | -------------
**RegionCode** | ***string** | REGION코드 | [optional] [default to null]
**PlacementGroupNo** | ***string** | 물리배치그룹번호 | [default to null]
