### ISSUE TITLE
data "ncloud_server_product" 블럭에서 VNKS 이미지를 인식하지 못합니다.

### ISSUE THREAD

**Issue by Jangab-water** [NaverCloudPlatform/terraform-provider-ncloud#253]
Terraform 을 사용하여 NKS를 재성성하던 도중, 동일한 코드에서 오류가 발생합니다.

```
data "ncloud_server_product" "specified_server_product_code" {
  server_image_product_code = "SW.VNKS.OS.LNX64.UBNTU.SVR2004.B050"

  filter {
    name = "product_type"
    values = [ var.product_type ]
  }

  filter {
    name = "cpu_count"
    values = [ var.cpu_count ]
  }

  filter {
    name = "memory_size"
    values = [ "${var.memory_size}GB" ]
  }

  filter {
    name = "product_code"
    values = [ "SSD" ]
    regex = true
  }
}
```

위의 코드로 `ncloud_server_product` data 블럭을 이용해 VNKS용(쿠버네티스용) 이미지를 가져오고, 이 이미지를 사용하여 NKS를 생성하는 로직입니다.

```
resource "ncloud_nks_cluster" "cluster" {
  k8s_version = data.ncloud_nks_versions.nks_ver.versions[0].value
  lb_private_subnet_no = ncloud_subnet.net_lb.id
  public_network = true
  subnet_no_list = [ ncloud_subnet.net_pub1.id ]
  name = "${var.prefix}-cluster"
  cluster_type = "SVR.VNKS.STAND.C002.M008.NET.SSD.B050.G002"
  login_key_name = ncloud_login_key.key.key_name
  vpc_no = ncloud_vpc.vpc.id
  zone = var.zone
}

resource "ncloud_nks_node_pool" "alpha" {
  cluster_uuid = ncloud_nks_cluster.cluster.uuid
  node_count = var.node_count
  node_pool_name = "${var.prefix}-alpha"
  product_code = data.ncloud_server_product.specified_server_product_code.product_code
}
```

상기 코드와 연계되는 부분이고, 이전에는 정상 작동하였으나 최근 릴리즈 이후로 400 에러와 함께 실패하고 있습니다.
기존 NCP에서 VNKS냐, VSVR이냐로 __서버용 이미지__와 __NKS용 이미지__를 구분하고 있는 것으로 이해하고 있는데, 아래 오류와 함께 실행이 중지되고 있습니다.

```
2022-12-01T16:51:18.498+0900 [INFO]  provider.terraform-provider-ncloud_v2.3.0: 2022/12/01 16:51:18 [ERROR] getVpcServerProductList error params={"regionCode":"KR","serverImageProductCode":"SW.VNKS.OS.LNX64.UBNTU.SVR2004.B050"}, err=Status: 400 Bad Request, Body: {
  "responseError": {
    "returnCode": "1413",
    "returnMessage": "Cannot find matched product code [SW.VNKS.OS.LNX64.UBNTU.SVR1804.B050]"
  }
}: timestamp=2022-12-01T16:51:18.498+0900
```

혹시 서버 이미지를 호출하는 부분이 바뀌었는지 릴리즈 Changelog를 확인했으나, server_product 혹은 server_image_product가 바뀐 이력은 없었습니다.

사용하고 있는 버전 정보 같이 전달드립니다.

```
Terraform v1.2.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/navercloudplatform/ncloud v2.3.0

Your version of Terraform is out of date! The latest version
is 1.3.6. You can update by downloading from https://www.terraform.io/downloads.html
```

**Comment by minosmlee** [comment]
안녕하세요.

Ncloud Terraform을 사용해주셔서 감사합니다.


----
예시로 들어주신 코드 중 datasource: ncloud_server_product 의 경우 vnks 용 이미지를 검색할 수 있도록 지원하고있지 않습니다.
해당 datasource는 VSVR 타입을 조회하기 위해 사용합니다. (이 부분에 대해서는 기존과 변경사항이 없습니다)

아마도 기존에 사용가능했다고 말씀하신 부분에 대해서는 `VNKS` 타입이아닌, `VSVR` 타입의 이미지 코드를 사용하시지 않았나 추측됩니다.

----
NKS 생성시 Product Code로 "VSVR" 타입을 사용하여도 사용이 불가능한 것은 아닙니다.

server_image_product_code 아규먼트가 필요한 이유는 해당 이미지에서 지원하는 서버 사양 코드를 조회하기 위함입니다.

따라서 아래 두 이미지 코드가 동일한 서버 사양을 지원한다면 서로간에 치환하여 사용 가능합니다.
SW.`VNKS`.OS.LNX64.UBNTU.SVR2004.B050
SW.`VSVR`.OS.LNX64.UBNTU.SVR2004.B050

물론 VNKS 타입의 경우 어떤 서버 사양을 지원하는지 여부는 Console 등을 통해 따로 확인해보셔야합니다.

----
이와 별개로 VNKS 타입의 서버 이미지를 조회하고 이에 따른 서버 사용을 조회할 수 있는 아래 두 Datasource 가 필요할 것 같습니다.
datasource: ncloud_nks_node_os_image
datasource: ncloud_nks_node_product

이 부분에 대해서는 올해 안에 지원 방안을 검토하여 적용하도록 하겠습니다.
그 전까지는 product code를 직접 입력하시거나, 아래와 같이 치환하여 사용하시기 바랍니다.
SW.`VNKS`.OS.LNX64.UBNTU.SVR2004.B050 -> SW.`VSVR`.OS.LNX64.UBNTU.SVR2004.B050

----
치환 가능한 `VNKS` 이미지 코드
SW.`VNKS`.OS.LNX64.UBNTU.SVR2004.B050 -> SW.`VSVR`.OS.LNX64.UBNTU.SVR2004.B050
SW.`VNKS`.OS.LNX64.UBNTU.SVR1804.B050 -> SW.`VSVR`.OS.LNX64.UBNTU.SVR1804.B050
SW.`VNKS`.OS.LNX64.UBNTU.SVR1604.B050 -> SW.`VSVR`.OS.LNX64.UBNTU.SVR1604.B050

---
사용 가능한 서버 사양 필터는 Console에서 노드풀 생성 메뉴 화면에서 확인가능합니다.

**Comment by minosmlee** [comment]
안녕하세요.

Ncloud Terraform을 사용해주셔서 감사합니다.

---
우선, NKS에서 Cluster와 Node Pool에 사용되는 code가 서로 다릅니다.

- Cluster Type : VNKS
  아래 두가지만 사용가능합니다. (Master Node에 대한 Image, Product Code는 제공하지 않습니다)
  - 10 ea : SVR.VNKS.STAND.C002.M008.NET.SSD.B050.G002
  - 50 ea : SVR.VNKS.STAND.C004.M016.NET.SSD.B050.G002

- Node Pool : VSVR
  아래 세가지 만 지원합니다.
  - SW.VSVR.OS.LNX64.UBNTU.SVR2004.B050  (ubuntu-20.04)
  - SW.VSVR.OS.LNX64.UBNTU.SVR1804.B050  (ubuntu-18.04)
  - SW.VSVR.OS.LNX64.UBNTU.SVR1604.B050  (ubuntu-16.04)

따라서 Node Pool 생성시에는 VSVR 타입을 사용해주셔야하고, VNKS 타입은 사용하시면 안됩니다.


----
Node Pool의 Image, Product Code를 찾기 위해 아래의 Datasource를 활용가능합니다.
- Datasource: ncloud_server_image
- Datasource: ncloud_server_images
- Datasource: ncloud_server_product
- Datasource: ncloud_server_products

추가로 아래 링크에서 image product name을 찾아 활용하실 수 있습니다.
https://github.com/NaverCloudPlatform/terraform-ncloud-docs/blob/main/docs/server_image_product.md
![image](https://user-images.githubusercontent.com/52672287/214524052-eabef830-02d5-4539-80fb-668a630b5232.png)


----
예시로 들어주신 코드 중 datasource: ncloud_server_product 의 경우 VNKS 용 이미지를 검색할 수 있도록 지원하고있지 않습니다.
(해당 datasource는 VSVR 타입을 조회하기 위해서만 사용합니다.)

이번 API 개선으로인해 server_product에서 VSVR 타입에 대한 Validation이 추가 되었기 때문에 에러가 발생한 부분입니다.


----
해당 내용에 대해 Terraform Docs에 설명을 보완하도록 하겠습니다.
