### ISSUE TITLE
VServer > Server

### ISSUE THREAD

**Issue by YuSungDuk** [NaverCloudPlatform/terraform-provider-ncloud#26]
#### Resource
- [x] resource_ncloud_server (Modify)

#### Data Source
- [x] data_source_ncloud_root_password (Modify)
- [x] data_source_ncloud_server (New)
- [x] ~data_source_ncloud_servers (New)~

#### API
- getServerInstanceList
- getServerInstanceDetail
- createServerInstances 
- startServerInstances 
- stopServerInstances 
- rebootServerInstances 
- terminateServerInstances 
- changeServerInstanceSpec 
- getRootPassword 
- getRootPasswordServerInstanceList

**Comment by sangkyu-kim** [comment]
![image](https://user-images.githubusercontent.com/40969251/92427846-8b3ceb00-f1c8-11ea-8404-8874aea18915.png)
