### ISSUE TITLE
"data.ncloud_network_acls.nacl[0].id" Attributes Reference BUG

### ISSUE THREAD

**Issue by stevetae** [NaverCloudPlatform/terraform-provider-ncloud#269]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform Ncloud Provider Version

```text
Terraform version :  v2.4.0
Ncloud Provider version : v2.3.13
```

### Affected Resource(s)

* resource "ncloud_network_acl_rule"

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

- https://gist.github.com/stevetae/5f3de18996a931f665e5c9c9c560ee39

### Expected Behavior

- Expect normal ID parsing by referring to ID properties.

### Actual Behavior

- Parsing the date the resource was created.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

- Nothing.

**Comment by youngmn** [comment]
For a more accurate analysis, could you also upload your terraform configuration file (.tf)?

ncloud_network_acls use example
```
data "ncloud_network_acls" "nacl" {}

resource "ncloud_network_acl_rule" "nacl_rule" {
   network_acl_no    = data.ncloud_network_acls.nacl.network_acls[0].id

```
