### ISSUE TITLE
기존인프라  import 과정 중에 문의드립니다.

### ISSUE THREAD

**Issue by teri0411** [NaverCloudPlatform/terraform-provider-ncloud#270]
안녕하세요
테라폼 import 작업중에 import하는 방법이 몇몇 리소스들에 한해 공식문서에 나와있지않고, 다른 리소스들을 import하는 방식으로 시도했을 때 에러를 뱉어서 import 방법에 대해 문의드립니다.

1. **route**

먼저 route에 관해서 **Import**에 대해 문의드립니다. 
또 NATGW (NAT Gateway) | VPCPEERING (VPC Peering) | VGW (Virtual Private Gateway) 이 3가지만 지원한다고 문서에 적혀있습니다. **target_type필드가 LOCAL, IGW일 때는 현재 생성할 방법이 있는지도 같이 문의드립니다**.
```

resource "ncloud_route" "NAT_TO_PRI_RT" {
  provider = ncloud.gov_prod
  route_table_no         = ncloud_route_table.simplatform-vpc-default-private-table.id
  destination_cidr_block = "0.0.0.0/0"
  target_type            = "NATGW"  // NATGW (NAT Gateway) | VPCPEERING (VPC Peering) | VGW (Virtual Private Gateway).
  target_name            = var.ncloud_nat_gateway_name
  target_no              = var.ncloud_nat_gateway_id
}

resource "ncloud_route" "IGW_TO_PUB_RT" {
  route_table_no         = ncloud_route_table.simplatform-vpc-default-public-table.id
  destination_cidr_block = "0.0.0.0/0"
  target_type            = "IGW"  // NATGW (NAT Gateway) | VPCPEERING (VPC Peering) | VGW (Virtual Private Gateway).
  target_name            = "INTERNET GATEWAY"
}
```
2. LoadBalancer단의 **Listener**와 **targetgroup attechment**

```
resource "ncloud_lb_target_group_attachment" "mqtt_tga" {
  target_group_no = ncloud_lb_target_group.mqtt-service.target_group_no
  target_no_list  = [var.node1_instance_id, var.node2_instance_id, var.node3_instance_id]
}
resource "ncloud_lb_listener" "istio1" {
  provider = ncloud.gov_prod
  load_balancer_no = ncloud_lb.istio-syste-istio-ingres-031d0.load_balancer_no
  protocol = "TCP"
  port = 15021
  target_group_no = ncloud_lb_target_group.nks-v2fczo6gpjgp3nyutmxcmnfqmm.target_group_no
}
```
이 두가지 resource를 import 할 때 route와 마찬가지로 어떤 값으로 해야할지 모르겠습니다.

예를들어 terraform import module.<폴더명>.listener.<명칭> <**콘솔에 보이는 listener번호 ??**>
로는 해봤지만 제대로 반환되지않는 것을 보아 해당 listener번호는 아닌것같고, 다른 고유값은 찾지 못했습니다.

++
ncloud_access_control_group_rule도 동일합니다.
import 시에 아래와 같음.

```
terraform import -var-file="test.tfvars" module.SecurityGroup.ncloud_access_control_group_rule.acg-rule 14548
Error: resource ncloud_access_control_group_rule doesn't support import
```

**정리하자면** 
- routetable의 route를 import 하는방법 
- LOCAL, IGW등 여러 target_type을 생성하는 방법
- **listener**, **targetgroup_attechment**, **ncloud_access_control_group_rule** import하는 방법입니다.

                                                                                            
* [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

**Comment by youngmn** [comment]
안녕하세요.
해당 문의 사항은 네이버클라우드 플랫폼 홈페이지를 통해 답변 드렸습니다.
감사합니다
