### ISSUE TITLE
AccTest: NetworkInterface update test failure

### ISSUE THREAD

**Issue by wonchulee** [NaverCloudPlatform/terraform-provider-ncloud#289]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform Ncloud Provider Version

```text
Terraform version : v1.5.2
Ncloud Provider version : main(2.3.18)
```

### Affected Resource(s)

* ncloud_network_interface

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# None
```

### Panic Output

```
go test -run TestAccresourceNcloudNetworkInterface_update ./...
?   	github.com/terraform-providers/terraform-provider-ncloud	[no test files]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x38 pc=0x103036a30]

goroutine 979 [running]:
github.com/terraform-providers/terraform-provider-ncloud/ncloud.getPublicIpInstanceOperationCode(...)
	/Users/wonchul/work/ncloud/terraform/terraform-provider-ncloud/ncloud/resource_ncloud_public_ip.go:492
github.com/terraform-providers/terraform-provider-ncloud/ncloud.waitForPublicIpDisassociation.func1()
	/Users/wonchul/work/ncloud/terraform/terraform-provider-ncloud/ncloud/resource_ncloud_public_ip.go:462 +0x60
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.(*StateChangeConf).WaitForStateContext.func1()
	/Users/wonchul/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/resource/state.go:110 +0x144
created by github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.(*StateChangeConf).WaitForStateContext
	/Users/wonchul/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/resource/state.go:83 +0x1a4
FAIL	github.com/terraform-providers/terraform-provider-ncloud/ncloud	265.053s
FAIL
```

### Expected Behavior

pass the test

### Actual Behavior

test paniced

### Steps to Reproduce

```
export NCLOUD_REGION=KR
export NCLOUD_ACCESS_KEY=xxx
export NCLOUD_SECRET_KEY=xxx
TF_ACC=1 go test ./internal/service/server/... -run=TestAccresourceNcloudNetworkInterface_update -v
```

**Comment by jungchanSon** [comment]
I'll work on this issue!

**Comment by wonchulee** [comment]
resolved
