### ISSUE TITLE
AccTest: NatGateway onlyRequiredParam test failure

### ISSUE THREAD

**Issue by wonchulee** [NaverCloudPlatform/terraform-provider-ncloud#292]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform Ncloud Provider Version

```text
Terraform version : v1.5.2
Ncloud Provider version : main(2.3.18)
```

### Affected Resource(s)

* ncloud_nat_gateway

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# None
```

### Debug Output

```
=== RUN   TestAccResourceNcloudNatGateway_onlyRequiredParam
    nat_gateway_test.go:84: Step 1/2 error: Error running apply: exit status 1

        Error: subnet_no is required when creating a new NATGW

          with ncloud_nat_gateway.nat_gateway,
          on terraform_plugin_test.tf line 8, in resource "ncloud_nat_gateway" "nat_gateway":
           8: resource "ncloud_nat_gateway" "nat_gateway" {

--- FAIL: TestAccResourceNcloudNatGateway_onlyRequiredParam (23.72s)
```

### Expected Behavior

Pass the test

### Actual Behavior

Test failure

### Steps to Reproduce

```
export NCLOUD_REGION=KR
export NCLOUD_ACCESS_KEY=xxx
export NCLOUD_SECRET_KEY=xxx
TF_ACC=1 go test ./internal/service/vpc/... -run=TestAccResourceNcloudNatGateway_onlyRequiredParam -v
```

**Comment by royroyee** [comment]
I'm working on `NatGateway` issue
