### ISSUE TITLE
ci: Introduce github action ci(lint, test, etc)

### ISSUE THREAD

**Issue by wonchulee** [NaverCloudPlatform/terraform-provider-ncloud#293]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

For a better Terraform Provider development environment, we need to build a CI environment using github action.
- linter (golangci-lint or others)
- test (unit test, acceptance test)
  - Add acceptance test in github action requires a new test account in ncloud, If it blocks this issue, we could separate the issue for the acceptance test.
- etc?

### References

* https://github.com/hashicorp/terraform-provider-aws
* https://github.com/hashicorp/terraform

**Comment by moto6** [comment]
@wonchulee can i try this issue?

**Comment by wonchulee** [comment]
@moto3z Sure
