### ISSUE TITLE
AccTest: block storage test failure

### ISSUE THREAD

**Issue by wonchulee** [NaverCloudPlatform/terraform-provider-ncloud#294]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform Ncloud Provider Version

```text
Terraform version : v1.5.2
Ncloud Provider version : main(2.3.18)
```

### Affected Resource(s)

* ncloud_block_storage

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# None
```

### Debug Output

```
=== RUN   TestAccResourceNcloudBlockStorage_vpc_basic
tf-storage-basic-2gpwm

    block_storage_test.go:63: Step 1/2 error: Check failed: Check 3/13 error: ncloud_block_storage.storage: Attribute 'name' expected "tf-storage-basic-2gpwmtf", got "tf-storage-basic-2gpwm-tf"
--- FAIL: TestAccResourceNcloudBlockStorage_vpc_basic (334.98s)
=== RUN   TestAccResourceNcloudBlockStorage_classic_ChangeServerInstance
    testing_new.go:84: Error running post-test destroy, there may be dangling resources: exit status 1

        Error: error waiting for BlockStorageInstance state to be "TERMINATED": unexpected state 'CREAT', wanted target 'TERMINATED'. last error: %!s(<nil>)

--- FAIL: TestAccResourceNcloudBlockStorage_classic_ChangeServerInstance (400.15s)
```

### Expected Behavior

Pass the test

### Actual Behavior

Test failure

### Steps to Reproduce

```
export NCLOUD_REGION=KR
export NCLOUD_ACCESS_KEY=xxx
export NCLOUD_SECRET_KEY=xxx
TF_ACC=1 go test ./internal/service/server/... -run TestAccResourceNcloudBlockStorage -v -timeout 30m
```

**Comment by jaehanbyun** [comment]
I'm working on this issue!

**Comment by wonchulee** [comment]
resolved https://github.com/NaverCloudPlatform/terraform-provider-ncloud/pull/338
