### ISSUE TITLE
Error when planning terraform

### ISSUE THREAD

**Issue by teri0411** [NaverCloudPlatform/terraform-provider-ncloud#302]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform Ncloud Provider Version

```text
Terraform version : 1.5.2
Ncloud Provider version : 2.3.16
```

### Affected Resource(s)

* ncloud_route_table_association
* ncloud_server
* ncloud_lb_listener
* ncloud_route

### Debug Output

│ Error: Request cancelled
│ 
│   with module.PriLbRta.ncloud_route_table_association.main[0],
│   on modules/network/RouteTableAssociation/main.tf line 4, in resource "ncloud_route_table_association" "main":
│    4: resource "ncloud_route_table_association" "main" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.

│ Error: Request cancelled
│ 
│   with module.K8sNodePool.ncloud_nks_node_pool.node_pool[0],
│   on modules/compute/K8sNodePool/main.tf line 4, in resource "ncloud_nks_node_pool" "node_pool":
│    4: resource "ncloud_nks_node_pool" "node_pool" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.

╷
│ Error: Plugin did not respond
│ 
│   with module.PubBastionRta.ncloud_route_table_association.main[0],
│   on modules/network/RouteTableAssociation/main.tf line 4, in resource "ncloud_route_table_association" "main":
│    4: resource "ncloud_route_table_association" "main" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.

│ Error: Plugin did not respond
│ 
│   with module.DeviceHubP8883Listener.ncloud_lb_listener.Ncloud_Listener[0],
│   on modules/compute/LoadBalancer/Listener/main.tf line 5, in resource "ncloud_lb_listener" "Ncloud_Listener":
│    5: resource "ncloud_lb_listener" "Ncloud_Listener" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.

### Panic Output

Stack trace from the terraform-provider-ncloud_v2.3.16 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xcfdab6]

goroutine 372 [running]:
github.com/terraform-providers/terraform-provider-ncloud/ncloud.getVpcLoadBalancerListenerTargetGroupNo(0xc0003bc740, {0xc000556116, 0x5})
        github.com/terraform-providers/terraform-provider-ncloud/ncloud/resource_ncloud_lb_listener.go:279 +0x156
github.com/terraform-providers/terraform-provider-ncloud/ncloud.getVpcLoadBalancerListener(0xc0003bc740, {0xc000556116, 0x5}, {0xc000556140, 0x8})
        github.com/terraform-providers/terraform-provider-ncloud/ncloud/resource_ncloud_lb_listener.go:257 +0x15e
github.com/terraform-providers/terraform-provider-ncloud/ncloud.resourceNcloudLbListenerRead({0x10fc7e0?, 0xc000376060?}, 0xc0006b8300, {0xde2be0?, 0xc0003bc740})
        github.com/terraform-providers/terraform-provider-ncloud/ncloud/resource_ncloud_lb_listener.go:145 +0x13c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0005b0ee0, {0x10fc7e0, 0xc000376060}, 0xd?, {0xde2be0, 0xc0003bc740})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:724 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0005b0ee0, {0x10fc7e0, 0xc000376060}, 0xc000698750, {0xde2be0, 0xc0003bc740})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0001ff920, {0x10fc7e0?, 0xc000283e90?}, 0xc000a88400)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:613 +0x4a5
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0005a3900, {0x10fc7e0?, 0xc000283170?}, 0xc000546240)
        github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/tf5server/server.go:748 +0x4b1
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0xf44460?, 0xc0005a3900}, {0x10fc7e0, 0xc000283170}, 0xc0002b0070, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0005f81e0, {0x11002c0, 0xc0005296c0}, 0xc000af85a0, 0xc0000aa9c0, 0x167bf90, 0x0)
        google.golang.org/grpc@v1.50.1/server.go:1340 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc0005f81e0, {0x11002c0, 0xc0005296c0}, 0xc000af85a0, 0x0)
        google.golang.org/grpc@v1.50.1/server.go:1713 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.50.1/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.50.1/server.go:963 +0x28a

Error: The terraform-provider-ncloud_v2.3.16 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

---
The issue does not exist in other ncloud accounts, but occurs only in one account. The terraform code is the same, but I don't know why.

**Comment by teri0411** [comment]
The same phenomenon occurs with 2.3.17 or 2.3.18 versions.

**Comment by wonchulee** [comment]
Hi, @teri0411, thanks for the reporting.
It looks like you used NKS and other resources, could you share the TF configuration you used when you encountered the issue?

**Comment by teri0411** [comment]
sure. @wonchulee

version.tf
```
terraform {
  cloud {
    organization = "xxx"
    workspaces {
      tags = ["xxx"]

    }
  }
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.45"
    }
    ncloud = {
      source  = "NaverCloudPlatform/ncloud"
      version = "~>2.3.16"
    }
  }
  required_version = ">= 0.15"
}
```
provider.tf

```
provider "ncloud" {
  access_key  = var.ncloud_access_key
  secret_key  = var.ncloud_secret_key
  region      = var.ncloud_region
  site        = var.ncloud_site
  support_vpc = var.ncloud_support_vpc
}
provider "aws" {
  region     = var.aws_region
  access_key = var.aws_access_key
  secret_key = var.aws_secret_key
}

```

cluster.tf

```
resource "ncloud_nks_cluster" "k8s_cluster" {
  count                = var.cloud_provider == "ncloud" ? 1 : 0
  cluster_type         = var.cluster_type.ncloud
  k8s_version          = var.master_version.ncloud[var.environment]
  login_key_name       = var.login_key_name
  name                 = var.name
  kube_network_plugin  = "cilium"
  vpc_no               = var.vpc_id
  lb_private_subnet_no = var.private_lb_subnet_id
  subnet_no_list       = var.Ncloud_subnet_ids
  zone                 = var.availability_zones.ncloud[0]
  log {
    audit = false
  }
}
```

nodepool.tf

```
resource "ncloud_nks_node_pool" "node_pool" {
  count          = var.cloud_provider == "ncloud" ? 1 : 0
  node_pool_name = var.name
  cluster_uuid   = var.k8s_cluster_id
  product_code   = var.instance_type.ncloud
  subnet_no      = var.Ncloud_subnet_ids
  node_count     = var.size.desired
  autoscale {
    enabled = true
    min     = var.size.min
    max     = var.size.max
  }
  lifecycle { create_before_destroy = true }
}
```

main.tf
```
##########
# Cluster 
##########

module "K8sCluster" {
  cloud_provider       = var.cloud_provider
  source               = "./modules/compute/K8sCluster"
  name                 = "xxx"
  vpc_id               = module.Vpc.id
  login_key_name       = module.LoginKey.name
  availability_zones   = local.constants.availability_zones
  cluster_type         = local.constants.k8s_cluster_type.medium
  master_version       = local.constants.k8s_master_version
  Ncloud_subnet_ids    = [module.PriK8sSubnet.subnet_id]
  AWS_subnet_ids       = [module.PriLbSubnet.subnet_id, module.PriK8sSubnet.subnet_id]
  private_lb_subnet_id = module.PriLbSubnet.subnet_id
  environment          = var.environment
  cluster_Role         = module.IAM.ClusterRole_arn
}

#######
# Node 
#######

module "K8sNodePool" {
  cloud_provider    = var.cloud_provider
  source            = "./modules/compute/K8sNodePool"
  name              = "xxx"
  instance_type     = local.constants.server_instance_type.medium_ssd
  k8s_cluster_id    = module.K8sCluster.id
  Ncloud_subnet_ids = module.PriK8sSubnet.subnet_id
  AWS_subnet_ids    = [module.PriLbSubnet.subnet_id, module.PriK8sSubnet.subnet_id]
  size              = local.constants.k8s_node_pool_size[var.environment]
  worker_Role       = module.IAM.WorkerRole_arn
  security_group_id = module.K8sCluster.security_group_id
  image_id          = local.constants.server_image_id.general
}
```

**Comment by consol-lee** [comment]
hello. @teri0411. 
I think I need to check a specific account.
Can you send me your account and terraform code(and module code) through inquiry?

Please refer to the address below.
- https://www.ncloud.com/support/question/service

thank you.

**Comment by teri0411** [comment]
I just sent you an inquiry with a code attached. Thank you.
