### ISSUE TITLE
`ncloud_auto_scaling_adjustment_types`

### ISSUE THREAD

**Issue by yoogledev** [NaverCloudPlatform/terraform-provider-ncloud#310]
### Description
AutoScaling Policy 생성시 참조 가능한 Adjustment Type 조회 DataSource 추가 개발

### New or Affected Resource(s)

* `ncloud_auto_scaling_adjustment_types`

### Potential Terraform Configuration

```hcl
resource "ncloud_launch_configuration" "lc" {
  name = "my-lc"
  server_image_product_code = "SPSW0LINUX000046"
  server_product_code = "SPSVRSSD00000003"
}

resource "ncloud_auto_scaling_group" "asg" {
  name = "my-auto"
  launch_configuration_no = ncloud_launch_configuration.lc.launch_configuration_no
  min_size = 1
  max_size = 1
  zone_no_list = ["2"]
  wait_for_capacity_timeout = "0"
}

resource "ncloud_auto_scaling_policy" "policy" {
  name = "my-policy"
  adjustment_type_code = data.ncloud_auto_scaling_adjustment_types.foo.types[0].code # 2. 조회된 Adjustment Type 참조
  scaling_adjustment = 2
  auto_scaling_group_no = ncloud_auto_scaling_group.asg.auto_scaling_group_no
}

# 1. Adjustment Type 전체 조회
# New Data Source
data "ncloud_auto_scaling_adjustment_types" "foo" {
}

```

### References
* [getAdjustmentTypeList(Classic)](https://api.ncloud-docs.com/docs/compute-autoscaling-getadjustmenttypelist)
* [getAdjustmentTypeList(VPC)](https://api.ncloud-docs.com/docs/compute-vautoscaling-autoscalinggroup-getadjustmenttypelist)
* [ncloud-sdk-go-v2(Classic)](https://github.com/NaverCloudPlatform/ncloud-sdk-go-v2/blob/c198af6b9a28b54b4ff0c375fffb1c9f81050e91/services/autoscaling/v2_api.go#L549-L621)
* [ncloud-sdk-go-v2(VPC)](https://github.com/NaverCloudPlatform/ncloud-sdk-go-v2/blob/c198af6b9a28b54b4ff0c375fffb1c9f81050e91/services/vautoscaling/v2_api.go#L549-L621)
* [Resource: ncloud_auto_scaling_policy](https://registry.terraform.io/providers/NaverCloudPlatform/ncloud/latest/docs/resources/auto_scaling_policy)

**Comment by royroyee** [comment]
I'm working on this issue!

**Comment by royroyee** [comment]
앗 ㅠ 제가 실수로 unassign 을 눌렀습니다 죄송합니다 ㅠ.ㅠ

**Comment by royroyee** [comment]
@yoogle96 @youngmn @wonchulee 

안녕하세요! 궁금한 점이 있어 질문드립니다.

`auto_scaling_adjustment_types` 가 `auto_scaling_policy` 에 있는 필드 요소인 것을 확인 후에 어떻게 진행해야 할지 알아보고 있는데요
```go
# auto_scaling_policy.go

"adjustment_type_code": {
				Type:             schema.TypeString,
				Required:         true,
				ValidateDiagFunc: ToDiagFunc(validation.StringInSlice([]string{"CHANG", "EXACT", "PRCNT"}, false)),
			},
```			
- 이 필드를 의미하는 것으로 이해했습니다.

그러면 DataSource 를 추가로 개발한다는 것은 `/service/autoscaling/` 디렉토리 안에 `auto_scaling_adjustment_types_data_source.go`, `auto_scaling_adjustment_types_data_source_test.go` 를 추가로 개발하는 것을 의미하는 것 같은데 맞을까요? 다른 리소스에는 오로지 type 을 위한 data source 가 없는 것 같아 헷갈립니다.


만약 그렇다면.. 
태그해주신 Reference 와 다른 리소스의 데이터 소스 부분들도 보면서 진행하고 있는데, `adjustment_type`  은 API 문서에도 필드 값이 작성되어 있진 않아서 어떤 필드 값이 있어야하는지 등 감을 잡기 좀 어렵습니다.


제가 좀 헤매고 있는 것 같은데, 어떤 순서와 방향으로 진행해야 하는지 도움을 받을 수 있을까요?
감사합니다!

**Comment by yoogledev** [comment]
@royroyee 

[`ncloud_server`](https://registry.terraform.io/providers/NaverCloudPlatform/ncloud/latest/docs/resources/server) Resource와 [`ncloud_server_images`](https://registry.terraform.io/providers/NaverCloudPlatform/ncloud/latest/docs/data-sources/server_images) DataSource 관계를 이해하시면 좋을것 같은데요!

server를 생성하려면 `server_product_code` 서버 코드를 (e.g. `SW.VSVR.OS.LNX64.CNTOS.0703.B050` ..) 필수로 넣어줘야합니다.
하지만, 해당 코드 값은 Ncloud 콘솔이나 가이드에 나와있지 않은 값인데요. 즉, API 를 호출해서 생성하고자하는 서버 이미지 코드를 갖아서 해당 속성 값에 넣어줘야합니다.

이 과정을 `ncloud_server_images` DataSource를 통해서 수행할 수 있는데요.
가이드에 나와있듯이 해당 DataSource로 전체 server image들을 조회해서 조회된 image 리스트들 중에 필요한 server image를 참조하여 `ncloud_server` Resource를 생성할 때 `server_image_product_code` 속성 값으로 사용합니다.

`ncloud_auto_scaling_adjustment_types` DataSource도 위 Server 리소스와 같이 `auto_scaling_policy` 리소스에 `adjustment_type_code` 속성 값에 DataSource로 참조해서 넣기 위해서 필요할 것 같습니다.
`adjustment_type`이 총 3개 밖에 없어서 ... 가이드 문서 보고 직접 값을 넣어줘도 될 것 같긴하지만... 그래도 data_source가 있으면 직접 하드코딩으로 값을 넣어주지 않아도 되어서 좋을것 같습니다.

말씀하신것 처럼 `auto_scaling_adjustment_types_data_source .go`, `auto_scaling_adjustment_types_data_source_test .go` 두 코드가 개발되어야 합니다. 그리고 API에 요청 파라미터가 없고 GET 하면 모든 코드들을 조회하는것이라, 스키마에 응답 파라미터에 대한 속성 값들만 리스트로 잘 정의하면 됩니다.

**Comment by royroyee** [comment]
@yoogle96 아 그렇군요! 그렇게 진행해볼게요. 감사합니다!
