### ISSUE TITLE
"GetOk()" does not recognize zero-value inputed as parameter

### ISSUE THREAD

**Issue by jungchanSon** [NaverCloudPlatform/terraform-provider-ncloud#344]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform Ncloud Provider Version

```text
Terraform version : 1.5.4
Ncloud Provider version : 2.3.18
```

### Affected Resource(s)

- [x]  autoscaling/...
- [x]  cdss/...
- [x]  classicloadbalancer/...
- [x]  loadbalancer/...
- [x]  devtools/...
- [x]  loginkey/...
- [x]  memberserverimage/...
- [x]  nasvolume/...
- [x]  nks/...
- [x]  server/...
- [x]  ses/...
- [x]  vpc/...

### Descriptions
GetOk 함수의 인자로 0 혹은 False값을 입력할 경우, ok 값으로 False가 나오게 됩니다. 
이때, 스키마값의 default가 0 혹은 False가 아닐 경우, 문제가 발생할 수 있습니다.
따라서, IntType 혹은 BoolType의 스키마가 GetOk 함수를 쓰는 곳을 확인해봐야 할 것 같습니다. 

### Example
auto_scaling_group.go
```go
reqParams := &vautoscaling.CreateAutoScalingGroupRequest{
		...
		DefaultCoolDown:          Int32PtrOrNil(d.GetOk("default_cooldown")),
                ...
	}
```

위 코드는 auto_scaling_group.go의 생성 요청 파라미터입니다.
DefaultCoolDown은 0~2147483647값을 가질 수 있고, default 값은 300입니다.(https://api.ncloud-docs.com/docs/compute-autoscaling-createautoscalinggroup)

하지만, DefaultCoolDown에 0을 입력할 경우, Int32PtrOrNil(d.GetOk("default_cooldown"))은 nil을 반환합니다.
최종적으로 DefaultCoolDown 파라미터는 nil로 입력되어 요청되기 때문에, 0으로 생성되어야 하지만, 300의 값을 가지고 생성이 됩니다. 

### Solution
저는 아래와 같이 해결하고 있습니다.
1. getok()를 get으로 변경 
```go
reqParams := &vautoscaling.CreateAutoScalingGroupRequest{
		...
		DefaultCoolDown:          Int32PtrOrNil(d.GetOk("default_cooldown")),             // old 
		DefaultCoolDown:          ncloud.Int32(int32(d.Get("default_cooldown").(int))), // new
                ...
	}
```

2. 스키마값에 default 값을 추가 
```
...
                     "default_cooldown": {
				Type:             schema.TypeInt,
				Optional:       true,
				Default:         300,           // add default value  
				ValidateDiagFunc: ToDiagFunc(validation.IntBetween(0, 2147483647)),
			},
...
``` 

### Debug Output
```go
func testAccAutoScalingGroupVpcConfig2() string {
	return fmt.Sprintf(`
resource "ncloud_vpc" "test" {
	ipv4_cidr_block    = "10.0.0.0/16"
}

resource "ncloud_subnet" "test" {
	vpc_no             = ncloud_vpc.test.vpc_no
	subnet             = "10.0.0.0/24"
	zone               = "KR-2"
	network_acl_no     = ncloud_vpc.test.default_network_acl_no
	subnet_type        = "PUBLIC"
	usage_type         = "GEN"
}

resource "ncloud_launch_configuration" "lc" {
	server_image_product_code = "SW.VSVR.OS.LNX64.CNTOS.0703.B050"
}

resource "ncloud_auto_scaling_group" "auto" {
	access_control_group_no_list = [ncloud_vpc.test.default_access_control_group_no]
	subnet_no = ncloud_subnet.test.subnet_no
	launch_configuration_no = ncloud_launch_configuration.lc.launch_configuration_no
	min_size = 1
	max_size = 1
	default_cooldown = 0
}`)
}
```
```
$ go test ./internal/service/autoscaling/auto_scaling_group_test.go -run=TestAccResourceNcloudAutoScalingGroup_vpc_basic2
--- FAIL: TestAccResourceNcloudAutoScalingGroup_vpc_basic2 (317.09s)
    auto_scaling_group_test.go:79: Step 1/1 error: Check failed: Check 2/2 error: ncloud_auto_scaling_group.auto: Attribute 'default_cooldown' expected "0", got "
300"
FAIL
FAIL    command-line-arguments  318.576s
FAIL
```

**Comment by jungchanSon** [comment]
i am working on "autoscaling/..."

**Comment by jungchanSon** [comment]
i am working on "cdss", "classicloadbalancer", "loadbalancer",  "loginkey", "memberserverimage"

**Comment by XIO1016** [comment]
I checked the following files, "nks", "server", "ses",  "vpc", but there was no problem.
