### ISSUE TITLE
Refactor the Route resource and data source to use the framework

### ISSUE THREAD

**Issue by royroyee** [NaverCloudPlatform/terraform-provider-ncloud#354]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Refactoring the `Route` resource, data source the Framework

### New or Affected Resource(s)

* ncloud_route_*
  * route.go
  * route_table.go
  * route_table_association.go
  * route_table_data_source.go
  * route_table_data_source_test.go
  * route_table_test.go
  * route_tables_data_source_test.go
  * route_test.go

### Potential Terraform Configuration

```hcl
None
```

### References

* [ncloud-route-docs](https://api.ncloud-docs.com/docs/networking-vpc-routetable-createroutetable)

**Comment by royroyee** [comment]
I'm currently working on this issue.

**Comment by wonchulee** [comment]
Development on this issue has stopped, so let's close it. If you'd like to work on it again, feel free to open it.
