### ISSUE TITLE
Refactor the Network ACL resource and data source to use the framework

### ISSUE THREAD

**Issue by ur2e** [NaverCloudPlatform/terraform-provider-ncloud#359]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* ncloud_network_acls
  * network_acl.go
  * network_acls_data_source.go
  * network_acls_data_source_test.go
  * network_acl_rule.go
  * network_acl_rule_test.go

### Potential Terraform Configuration

```hcl
None
```

### References

* [Network ACL Docs](https://api.ncloud-docs.com/docs/networking-vpc-networkacl-createnetworkacl)

**Comment by ur2e** [comment]
I'm currently working on this issue.

**Comment by wonchulee** [comment]
Development on this issue has stopped, so let's close it. If you'd like to work on it again, feel free to open it.
