### ISSUE TITLE
Provider Review

### ISSUE THREAD

**Issue by mbfrahry** [NaverCloudPlatform/terraform-provider-ncloud#38]
Hello! My name is Matthew Frahry and I'm from the Terraform Ecosystem Team. @tracypholmes and I have been reviewing your provider and we've seen some great stuff around your provider and we're excited to bring it into our ecosystem. There are issues with it though that have been listed below in order of importance. If you see a specific issue on one of the resources, please take that feedback and apply it to all resources that show that same issue.

- [x] Many of the attribute names are prefixed by the resource name (ie. the `block_storage` attributes look like `block_storage_name`. These prefixes can be removed as it's implied that the attributes you're using are referencing the resource itself.
  => fixed (#39)
- [x] Having the ability to use the [most recent](https://github.com/NaverCloudPlatform/terraform-provider-ncloud/blob/master/ncloud/data_source_ncloud_access_control_group_test.go#L58) access control group is tricky because a user's configuration could change unexpectedly when another access control group is added. Is there a good use case that I'm not seeing for this functionality? 
  -> fixed by #89 
- [x] If ever we get more than one [result](https://github.com/NaverCloudPlatform/terraform-provider-ncloud/blob/master/ncloud/data_source_ncloud_access_control_group.go#L95), we need to error out because we don't know exactly which resource the user is looking for. 
  -> fixed by #89 
- [x] Is there a reason this [error](https://github.com/NaverCloudPlatform/terraform-provider-ncloud/blob/master/ncloud/data_source_ncloud_common.go#L26) is ignored. It seems like this could cause problems if we hit it and don't address it
- [x] If we don't find a resource (ie. 404) we need to remove that value from the state file so Terraform can try and create the resource.
If we look [here](https://github.com/NaverCloudPlatform/terraform-provider-ncloud/blob/0cc93594efa2a982de5e6835740533ca5d9de6f9/ncloud/resource_ncloud_nas_volume.go#L219), we can add 
```
if err != nil {
  if err == 404  { // ie. resource not found
    log.Printf("unable to find resource: %s", d.Id())
    d.SetId("")
  } else {
      return err
  }
}
```
- [x] You have some [resources](https://github.com/NaverCloudPlatform/terraform-provider-ncloud/blob/0cc93594efa2a982de5e6835740533ca5d9de6f9/ncloud/resource_ncloud_load_balancer_ssl_certificate.go#L17) that have import support but don't test whether everything gets imported correctly. At the end of every test I'd throw this block
```
{
	ResourceName:      resourceName,
	ImportState:       true,
	ImportStateVerify: true,
},
``` 
as the last [test step](https://github.com/NaverCloudPlatform/terraform-provider-ncloud/blob/0cc93594efa2a982de5e6835740533ca5d9de6f9/ncloud/resource_ncloud_load_balancer_ssl_certificate_test.go#L105) for every resource test that has import support.
  => fixed by #85 
- [x] [This](https://github.com/NaverCloudPlatform/terraform-provider-ncloud/blob/0cc93594efa2a982de5e6835740533ca5d9de6f9/ncloud/resource_ncloud_load_balancer_ssl_certificate_test.go#L38) poses a security risk. I'd suggest creating a new public/private key pair as shown in this [test](https://github.com/terraform-providers/terraform-provider-aws/blob/644235be847634ded0de0d18ca3935018e0899ae/aws/resource_aws_acm_certificate_test.go#L571)
- [x] We should put a note in this [documentation](https://github.com/NaverCloudPlatform/terraform-provider-ncloud/blob/master/website/docs/r/login_key.html.markdown) and this [documentation](https://github.com/NaverCloudPlatform/terraform-provider-ncloud/blob/master/website/docs/d/root_password.html.markdown) that warns users that they are writing out their private keys that give access to their environment to the state file and should be wary when using version control and this resource
  -> fixed by #83 
- [x] `block storage no` is a confusing attribute name. Is this the id of the resource or something else? 
- [x] [`block_storage_size_gb`](https://github.com/NaverCloudPlatform/terraform-provider-ncloud/blob/master/ncloud/resource_ncloud_block_storage.go#L36) This note is confusing, it looks like you're telling the user to change their state-file unless i'm reading into it wrong. Can you please elaborate on this message?
  -> fixed by #78 
- [x] `code` & `code_name` scattered over the documentation across multiple attributes (`disk_type`, etc). Could you please elaborate on what these are referring to
  -> fixed #79 
- [x] [Here](https://github.com/NaverCloudPlatform/terraform-provider-ncloud/blob/master/ncloud/provider.go#L16) the first value of EnvDefaultFunc is the default value. This should be set to any empty string if there is no default value.
  -> fixed by #50 
- [x] In the docs for setting up the provider, you say region is Optional but [here](https://github.com/NaverCloudPlatform/terraform-provider-ncloud/blob/master/ncloud/provider.go#L27) it is required.
  -> fixed by #52 
- [x] [Dates](https://github.com/NaverCloudPlatform/terraform-provider-ncloud/blob/master/ncloud/data_source_ncloud_access_control_group.go#L39) aren't the most useful attribute to track in Terraform. I'd suggest removing them from all resources/datasources unless you feel they are needed.
  -> fixed by #54
- [x] Many of the [validation functions](https://github.com/NaverCloudPlatform/terraform-provider-ncloud/blob/ea71e3140d3ac98306a75c3644f05cbdc5eb7649/ncloud/validators.go#L59) that you've implemented are [helpers](https://github.com/hashicorp/terraform/blob/master/helper/validation/validation.go#L51) inside of terraform. I'd suggest swapping to the Terraform validation functions for simplicity. 
  -> fixed by #55 
- [x] This [validation](https://github.com/NaverCloudPlatform/terraform-provider-ncloud/blob/0cc93594efa2a982de5e6835740533ca5d9de6f9/ncloud/resource_ncloud_nas_volume.go#L45) looks like it wants to use this [function](https://github.com/hashicorp/terraform/blob/master/helper/validation/validation.go#L130) instead as the value can be either `CIFS` or `NFS`.
  -> fixed by #56 
- [x] Many of the [values](https://github.com/NaverCloudPlatform/terraform-provider-ncloud/blob/0cc93594efa2a982de5e6835740533ca5d9de6f9/ncloud/resource_ncloud_nas_volume.go#L309) you are grabbing while making the create request are Optional. It's best practice to use `d.GetOk()` and make sure the value is set in the config file before we pass an empty value to the api. 
  => fixed by #59 
- [x] [This](https://github.com/NaverCloudPlatform/terraform-provider-ncloud/blob/0cc93594efa2a982de5e6835740533ca5d9de6f9/ncloud/resource_ncloud_nas_volume.go#L359) logic can be cleaned up significantly by using [StateChangeConf](https://github.com/terraform-providers/terraform-provider-aws/blob/67b94cf529a7a45cc3e2c8f814d9ec604ac1dd08/aws/resource_aws_batch_job_queue.go#L65)
  => fixed by #62 
- [x] [This](https://github.com/NaverCloudPlatform/terraform-provider-ncloud/blob/0cc93594efa2a982de5e6835740533ca5d9de6f9/ncloud/resource_ncloud_nas_volume_test.go#L62) is enabled by default so we can remove it.
  => fixed by #64 
- [x] It looks like this [destroy function](https://github.com/NaverCloudPlatform/terraform-provider-ncloud/blob/0cc93594efa2a982de5e6835740533ca5d9de6f9/ncloud/resource_ncloud_nas_volume_test.go#L143) is unneeded as it's one line pointing to another function
  => fixed by #65 
- [x] It looks like  [this](https://github.com/NaverCloudPlatform/terraform-provider-ncloud/blob/0cc93594efa2a982de5e6835740533ca5d9de6f9/ncloud/zone.go) is missing some tests. Can we get those added to confirm this functionality
  => fixed by #66 
- [x] It looks like MEMO.md is empty, is it needed or can we remove it?
  => MEMO.md  file is removed.
- [x] In [https://github.com/NaverCloudPlatform/terraform-provider-ncloud/blob/master/GNUmakefile#L63](GNUMakefile) there is an added command we can remove in favor of our build/release process that will publish across these platforms.
  => removed ad added command (#42)
- [x] Having a list of rules inside of your [rules datasource](https://github.com/NaverCloudPlatform/terraform-provider-ncloud/blob/master/ncloud/data_source_ncloud_access_control_groups.go#L47) isn't ideal and can cause a lot of clutter in the state. Instead, I'd suggest you save a list of ids inside of this resource that can then be piped into the other rule datasource if needed. 
  => fixed by #67 
- [x] [Argument references](https://github.com/NaverCloudPlatform/terraform-provider-ncloud/blob/master/website/docs/r/block_storage.html.markdown#argument-reference) should be written so the `Required` arguments are listed first
  => fixed by #68 
- [x] Inside of your documentation you are listing attributes in both the `Argument Reference` and the `Attributes Reference`. If an attribute is listed in the `Argument Reference` , it doesn't have to be in the `Attribute Reference` 
  => fixed by #69 
- [x] Also for [`block_storage_size_gb`](https://github.com/NaverCloudPlatform/terraform-provider-ncloud/blob/master/ncloud/resource_ncloud_block_storage.go#L36), you state "Enter the block storage size to be created. You can enter in GB units, and you can only enter up to 1000 GB." We can force this check with `ValidateFunc: validation.IntAtMost(1000),`
  => fixed #44
- [x]  [Server](https://github.com/NaverCloudPlatform/terraform-provider-ncloud/blob/master/website/docs/r/server.html.markdown#argument-reference) I haven't seen "Conditional" used in the documentation before. Is there a reason you've assigned some of your attributes this (Ex: `server_image_product_code`). "Required" or "Optional" are usually the only choices in the documentation. Can you please elaborate on what you mean by `Conditional`?
  => fixed #76

**Comment by YuSungDuk** [comment]
@mbfrahry Thanks you. I'll check your review.

**Comment by YuSungDuk** [comment]
NCLOUD load balancer don't support tls self signed certificate, so we can't use `tls` provider

**Comment by YuSungDuk** [comment]
`block storage no` is a confusing attribute name. Is this the id of the resource or something else?
=> I can't find `block storage no`. where did you find this ??

**Comment by mbfrahry** [comment]
```
NCLOUD load balancer don't support tls self signed certificate, so we can't use tls provider. And This is for test not real
```
This makes sense to me! I'm fine keeping it in

**Comment by mbfrahry** [comment]
Anything with `_no` at the end could be seen as a confusing attribute name. For instance [instance_no](https://github.com/NaverCloudPlatform/terraform-provider-ncloud/blob/master/ncloud/resource_ncloud_block_storage.go#L61),  [server_instance_no](https://github.com/NaverCloudPlatform/terraform-provider-ncloud/blob/master/ncloud/resource_ncloud_block_storage.go#L32), and [member_server_image_no](https://github.com/NaverCloudPlatform/terraform-provider-ncloud/blob/master/ncloud/resource_ncloud_server.go#L41) to name a few. Ending with `_name` or `_id` would be more appropriate.

**Comment by YuSungDuk** [comment]
@mbfrahry Thank you. I'll change `_no` to `_id`.

**Comment by YuSungDuk** [comment]
> [Server](https://github.com/NaverCloudPlatform/terraform-provider-ncloud/blob/master/website/docs/r/server.html.markdown#argument-reference) I haven't seen "Conditional" used in the documentation before. Is there a reason you've assigned some of your attributes this (Ex: `server_image_product_code`). "Required" or "Optional" are usually the only choices in the documentation. Can you please elaborate on what you mean by `Conditional`?
=>

**Comment by YuSungDuk** [comment]
@mbfrahry We have fixed code by your review. Please check this repository and my comments. Thank you.

**Comment by mbfrahry** [comment]
Hey @YuSungDuk. Thank you for taking the time to go over the review and address my comments. Things are mostly there, it just looks like some things were missed that I've listed below. I believe when that gets fixed up we can go ahead and get this provider into our ecosystem. 

- [ ] [most_recent](https://github.com/NaverCloudPlatform/terraform-provider-ncloud/blob/5391d5a73742a78817d895f8e1eb4b9a3bf6ed22/ncloud/data_source_ncloud_member_server_image.go#L40) is still used in quite a few places in the provider. Please remove all instances of this attribute from this provider.

- [ ] Relatedly, we need to error if we find more than one of the resource because we aren't entirely sure that we got the resource we requested. (ie. https://github.com/NaverCloudPlatform/terraform-provider-ncloud/blob/master/ncloud/data_source_ncloud_member_server_image.go#L188)

- [ ] This [error](https://github.com/NaverCloudPlatform/terraform-provider-ncloud/blob/master/ncloud/data_source_ncloud_common.go#L26) is still being ignored and should be handled. 

- [ ] There are still some [channels](https://github.com/NaverCloudPlatform/terraform-provider-ncloud/blob/master/ncloud/resource_ncloud_login_key.go#L171)  being used that should be replaced with WaitForStateConf.

**Comment by YuSungDuk** [comment]
@mbfrahry We have fixed code by your additional review. Please check this repository. 
Have a nice day. Thank you.

**Comment by mbfrahry** [comment]
Great! Thank you for the efforts here. I'll go ahead and close this issue and we'll move forward.
