### ISSUE TITLE
[New Resource]: Object Storage & Global CDN

### ISSUE THREAD

**Issue by jinlee1703** [NaverCloudPlatform/terraform-provider-ncloud#395]
### Description

I want to use NCP's Object Storage and Global CDN, but I couldn't find it in the [docs](https://github.com/NaverCloudPlatform/terraform-ncloud-docs). Could you please add some resources?

### References

- [NCP Object Storage Document](https://www.ncloud.com/product/storage/objectStorage)
- [NCP Global CDN Document](https://www.ncloud.com/product/contentDelivery/globalCdn)

### Would you like to implement a fix?

None

**Comment by probepark** [comment]
any update?

**Comment by wonchulee** [comment]
Object Storage 지원 추가 예정입니다. (코드 반영되었으나 아직 릴리즈 되지 않았음) 참고 부탁드립니다.
Global CDN은 지원하지 않을 예정이며, CDN 서비스 중 하나인 Global Edge를 추후 추가할 예정입니다.
