### ISSUE TITLE
ncloud_server에서 KVM 이미지 사용

### ISSUE THREAD

**Issue by song2park** [NaverCloudPlatform/terraform-provider-ncloud#422]
### Description

`ncloud_server`에서 `server_image_product_code`에 KVM용 코드를 입력 시 다음과 같은 에러 메시지 발생
```
│ Error: Status: 400 Bad Request, Body: {
│   "responseError": {
│     "returnCode": "1401",
│     "returnMessage": "Not found server product. Please check the product code, region, and zone."
│   }
│ }
```

해당 server 블럭은 다음과 같습니다.
```
resource "ncloud_server" "server" {
  subnet_no = var.subnet_no
  name = var.server_name
  server_image_product_code = "SW.VSVR.OS.LNX64.UBNTU.SVR22.G003"
  login_key_name = var.login_key_name
  is_protect_server_termination = false
  init_script_no = var.init_script != null ? ncloud_init_script.init.0.id : null
}
```
`server_image_product.md`문서에도 G1/G2에 대한 이미지 코드만 나열되어 있더라고요.
NKS에서는 kvm 타입의 인스턴스로 잘 생성되는 것을 확인했는데, 혹시 Terraform에서 일반 server 생성 시 아직 kvm은 지원하지 않는 것인가요?

### Would you like to implement a fix?

None

**Comment by youngmn** [comment]
@song2park 안녕하세요. 
Ncloud Terraform Provider 를 사용해 주셔서 감사합니다.

현재 G1/G2 만 지원하고 있으며, KVM 서버 생성은 아직 지원되지 않고 있습니다.

정확한 추가 일정을 답변 드릴 수는 없으나 향후 추가하도록 하겠습니다.

감사합니다.
