### ISSUE TITLE
mysql slave 지원 여부와 data acg 블록 vpc 지원 여부가 궁금합니다. 

### ISSUE THREAD

**Issue by yoshikime** [NaverCloudPlatform/terraform-provider-ncloud#429]
### Description

안녕하세요. 
mysql 서버를 생성하고 나니 slave 서버 추가는 테라폼에서 지원이 안되더군요. 지원 예정이 있는지 궁금합니다. 
또한 문서에는 나와있지 않은데 data "ncloud_access_control_group_rule" 을 vpc환경에서는 사용이 불가능하다고 나오더라구요. 이것도 vpc 환경에서 지원예정이 있을까요? 
추가로 data "ncloud_root_password" 도 호출하면 현재 임시로 사용할 수 없다는 에러 메세지가 나오고 있는데, 확인 부탁드립니다. 

### References

│ Error: data source `ncloud_access_control_rule` doesn't support vpc
│
│   with module.mysql.data.ncloud_access_control_rule.mysql,
│   on mysql\acg.tf line 5, in data "ncloud_access_control_rule" "mysql":
│    5: data "ncloud_access_control_rule" "mysql" {

### Would you like to implement a fix?

None

**Comment by youngmn** [comment]
https://registry.terraform.io/providers/NaverCloudPlatform/ncloud/latest/docs/resources/mysql_slave
