### ISSUE TITLE
ncloud_mysql DB 스펙 변경 관련하여 질문드립니다.

### ISSUE THREAD

**Issue by freeeeedev** [NaverCloudPlatform/terraform-provider-ncloud#431]
### Description

안녕하세요.
현재 저는 ncloud provider 3.1.1 를 사용하여 terraform으로 Cloud DB for MySQL을 관리하고 있습니다.
그런데 DB 스펙을 변경하기 위해서 product_code를 변경하면, 콘솔처럼 status가 업그레이드로 변경되면서 스펙 변경이 진행되지 않고, DB server가 삭제된 후 다시 생성됩니다.

terraform으로 운영중인 DB server의 스펙을 변경할 수 있는 방법이 있다면, 안내해주시면 감사하겠습니다.

### Would you like to implement a fix?

None

**Comment by consol-lee** [comment]
안녕하세요.
현재 Ncloud Provider에서는 cloud db for mysql의 수정은 제공하고 있지 않습니다.
콘솔을 통해 수정하신 다음 코드 내부에서 맞추어 사용하시는 것을 권유드립니다.
