### ISSUE TITLE
3.0 메이저 버전 업데이트가 되었는데, 알려진 Breaking Change가 따로 없나요? Major 업데이트인 이유가 무엇일까요?

### ISSUE THREAD

**Issue by a3626a** [NaverCloudPlatform/terraform-provider-ncloud#472]
### Description

2.x에서 3.x로 큰 조치 없이 업데이트 해도 괜찮을까요?

### Would you like to implement a fix?

None

**Comment by wonchulee** [comment]
안녕하세요, terraform provider 내부에서 사용하는 protocol 버전을 6까지 확장하면서, major 버전을 변경하게 되었습니다.
provider가 제공하는 리소스와 관련된 breaking change는 없으며, 지원하는 Terraform Cli 최소 버전이 변경되었습니다. 참고 부탁드립니다.

- protocol 5: Terraform CLI 0.12 and later
- protocol 6: Terraform CLI 1.0 and later (https://developer.hashicorp.com/terraform/plugin/mux/combining-protocol-version-6-providers)
