### ISSUE TITLE
Support Cloud DB for MySQL

### ISSUE THREAD

**Issue by YuSungDuk** [NaverCloudPlatform/terraform-provider-ncloud#8]
https://apidocs.ncloud.com/en/database/cloud_db
https://github.com/NaverCloudPlatform/ncloud-sdk-go-v2/blob/master/services/clouddb/README.md

**Comment by wonchulee** [comment]
https://github.com/NaverCloudPlatform/terraform-provider-ncloud/issues/282
I think it would be better to prioritize working with Cloud db in VPC environment instead of Classic environment, so closing this issue.
